### ISSUE TITLE
Error 404 after install

### ISSUE THREAD

**Issue by sigmap** [BookStackApp/BookStack#1050]
Running bookstack with a vhost that points to bookstack.localhost
From `httpd-vhosts.conf` 
```
<VirtualHost *:80>
       ServerAlias bookstack.localhost
       #Redirect 301 / https://bookstack.localhost
       DocumentRoot "C:/xampp/subdomains/BookStack/public/"
        <Directory "C:/xampp/subdomains/BookStack/public/">
        Options None
        Order allow,deny
        Allow from all
    </Directory>
</VirtualHost>
```
`BookStack/Public/.htaccess` 
```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    Options +SymLinksIfOwnerMatch
    RewriteEngine On

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```
Am I missing something?

**Configuration**
 - Exact BookStack Version: 0.24.1
 - PHP Version: 7.2.9
 - Hosting Method:  xampp/Apache

**Comment by ssddanbrown** [comment]
- Are you redirected to a certain URL when you try to access your instance?
- Is apache mod_rewrite enabled?
- Is the 404 page an apache (Blank-looking) page or a BookStack page (Non-blank looking).

**Comment by sigmap** [comment]
I commented out the redirect to see if I could at least access it first. The redirect doesn't happen and is a non-issue atm.

I tried a clean git clone this time. Process gets a 500 error on chrome, but a blank page in firefox.
```
<VirtualHost *:80>
       ServerAlias book.localhost
       #Redirect 301 / https://book.localhost
       <Directory "C:/xampp/htdocs/book/public/">
            #Options None
            #Order allow,deny
            #Allow from all
            Require all granted
            AllowOverride All
            #Options +Indexes
       </Directory>
       DocumentRoot "C:/xampp/htdocs/book/public/"
       ServerName book.localhost
</VirtualHost>
```

**Comment by sigmap** [comment]
I decided to check the log. I don't think this is supposed to happen.

```
[php7:error] [pid 8120:tid 1644] [client 127.0.0.1:11471] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstack.settings' doesn't exist in C:\\xampp\\htdocs\\book\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:77\nStack trace:\n#0 C:\\xampp\\htdocs\\book\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php(77): PDO->prepare('select * from `...', Array)\n#1 C:\\xampp\\htdocs\\book\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(326): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select * from `...')\n#2 C:\\xampp\\htdocs\\book\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)\n#3 C:\\xampp\\htdocs\\book\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))\n#4 C:\\xampp\\htdocs\\book\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(333): Illuminate\\Database\\Connection->run('sele in C:\\xampp\\htdocs\\book\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php on line 664
[Mon Nov 05 22:30:14.681522 2018] [php7:error] [pid 8120:tid 1644] [client 127.0.0.1:11471] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstack.settings' doesn't exist in C:\\xampp\\htdocs\\book\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php:77\nStack trace:\n#0 C:\\xampp\\htdocs\\book\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOConnection.php(77): PDO->prepare('select * from `...', Array)\n#1 C:\\xampp\\htdocs\\book\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(326): Doctrine\\DBAL\\Driver\\PDOConnection->prepare('select * from `...')\n#2 C:\\xampp\\htdocs\\book\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)\n#3 C:\\xampp\\htdocs\\book\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))\n#4 C:\\xampp\\htdocs\\book\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(333): Illuminate\\Database\\Connection->run('sele in C:\\xampp\\htdocs\\book\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php on line 664
```

**Comment by sigmap** [comment]
I tried running `php artisan migrate` and it did say the database was migrated successfully, but then there was this afterwards
```
 [Doctrine\DBAL\Driver\PDOException]
 SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.



 [PDOException]
 SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
```

**Comment by sigmap** [comment]
Update 3:

ditched the database I created originally and made a new one set collation to `utf8mb4_unicode_ci`. So it seems it's sensitive to the collation.

**Comment by ssddanbrown** [comment]
@sigmap Thanks for confirming it's resolved. Happy to hear you got things working.
