### ISSUE TITLE
PDF Export Unknown Error (possibly linked to copy+paste tables

### ISSUE THREAD

**Issue by Ethanb00** [BookStackApp/BookStack#1330]
**Describe the bug**
Hey mate.

I was working up some documentation where I was copying and pasting content from the Salesforce Setup/Admin section (basically, tables of permissions, see below). They copy and paste ok, but when I go to export to PDF, it throws the "An unknown error occurred" message.

Many thanks,
Ethan

**Steps To Reproduce**
1. Using Salesforce Setup/Admin section, copy and paste a value/checkbox table into Bookstack
2. Clean up table sizing for aesthetics.  
3. Save the page
4. Export to PDF
5. See error

I reviewed some of the previously reported PDF issues and the suggested composer install + cache clears didn't help. I think it's pretty unlikely to be the issue.  Other pages export to PDF just fine. 
**Expected behavior**
A PDF export 

**Screenshots**
![image](https://user-images.githubusercontent.com/5893479/54287299-c599dd80-457b-11e9-8c36-7f73e7486e59.png)

![image](https://user-images.githubusercontent.com/5893479/54286849-f9283800-457a-11e9-865a-c7ac15984c77.png)

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): BookStack v0.25.1
 - PHP Version: PHP 7.0.33-0ubuntu0.16.04.2 
 - Hosting Method (Nginx/Apache/Docker): Apache

**Additional context**
Laravel.log:

<details><summary>Details</summary>
<p>

```
 production.ERROR: Call to a member function get_cellmap() on null {"userId":1,"email":"[REDACTED]","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member $
[stacktrace]
#0 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\TableCell->reflow(NULL)
#1 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameReflower/TableRow.php(52): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow()
#2 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\TableRow->reflow(Object(Dompdf\\FrameDecorator\\Block))
#3 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameReflower/Block.php(845): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow(Object(Dompdf\\FrameDecorator\\Block))
#4 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Block->reflow(Object(Dompdf\\FrameDecorator\\Block))
#5 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameReflower/Block.php(845): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow(Object(Dompdf\\FrameDecorator\\Block))
#6 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Block->reflow(Object(Dompdf\\FrameDecorator\\Block))
#7 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameReflower/Block.php(845): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow(Object(Dompdf\\FrameDecorator\\Block))
#8 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Block->reflow(Object(Dompdf\\FrameDecorator\\Block))
#9 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameReflower/Block.php(845): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow(Object(Dompdf\\FrameDecorator\\Block))
#10 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Block->reflow(Object(Dompdf\\FrameDecorator\\Block))
#11 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameReflower/Block.php(845): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow(Object(Dompdf\\FrameDecorator\\Block))
#12 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Block->reflow(Object(Dompdf\\FrameDecorator\\Block))
#13 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameReflower/Block.php(845): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow(Object(Dompdf\\FrameDecorator\\Block))
#14 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Block->reflow(Object(Dompdf\\FrameDecorator\\Block))
#15 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameReflower/Block.php(845): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow(Object(Dompdf\\FrameDecorator\\Block))
#16 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Block->reflow(Object(Dompdf\\FrameDecorator\\Block))
#17 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameReflower/Block.php(845): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow(Object(Dompdf\\FrameDecorator\\Block))
#18 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Block->reflow(NULL)
#19 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameReflower/Page.php(141): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow()
#20 /var/www/bookstack/vendor/dompdf/dompdf/src/FrameDecorator/AbstractFrameDecorator.php(895): Dompdf\\FrameReflower\\Page->reflow(NULL)
#21 /var/www/bookstack/vendor/dompdf/dompdf/src/Dompdf.php(847): Dompdf\\FrameDecorator\\AbstractFrameDecorator->reflow()
#22 /var/www/bookstack/vendor/barryvdh/laravel-dompdf/src/PDF.php(200): Dompdf\\Dompdf->render()
#23 /var/www/bookstack/vendor/barryvdh/laravel-dompdf/src/PDF.php(146): Barryvdh\\DomPDF\\PDF->render()
#24 /var/www/bookstack/app/Entities/ExportService.php(140): Barryvdh\\DomPDF\\PDF->output()
#25 /var/www/bookstack/app/Entities/ExportService.php(86): BookStack\\Entities\\ExportService->htmlToPdf('<!doctype html>...')
#26 /var/www/bookstack/app/Http/Controllers/PageController.php(504): BookStack\\Entities\\ExportService->pageToPdf(Object(BookStack\\Entities\\Page))
```

</p>
</details>

**Comment by ssddanbrown** [comment]
Hi @Ethanb00, 
Sorry, forgot to come back to properly validate & dig into this one!

Since this is so old I'm going to close it off, but feel free to raise a new issue if it's still a problem for you on the latest version.
