### ISSUE TITLE
Unable to run bookstack with php 7.4

### ISSUE THREAD

**Issue by amo13** [BookStackApp/BookStack#1974]
Hey, I just spent a lot of time to find out that bookstack does not work on my archlinux with php 7.4. 

My nginx config:
```
server {
    root /usr/share/webapps/bookstack/public;
    listen       80;
    server_name  localhost;

    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # default fastcgi_params
        include fastcgi_params;

        # fastcgi settings
        fastcgi_pass			unix:/run/php-fpm/php-fpm.sock;
        fastcgi_index			index.php;
        
        fastcgi_buffers			8 16k;
        fastcgi_buffer_size		32k;

        # fastcgi params
        fastcgi_param DOCUMENT_ROOT	$realpath_root;
        fastcgi_param SCRIPT_FILENAME	$realpath_root$fastcgi_script_name;
    }
}
```
Both the php-fpm and php73-fpm services are running fine. When I switch to php 7.3, the page loads and everything works. The only thing I do is change `fastcgi_pass unix:/run/php-fpm/php-fpm.sock;` to `fastcgi_pass unix:/run/php73-fpm/php-fpm.sock;` in the nginx config above.

When trying to run bookstack on php 7.4, I get a blank page on http://localhost an following errors in my nginx log:
```
Mär 19 12:52:02 amaury-pc nginx[5191]: 2020/03/19 12:52:02 [error] 5191#5191: *14 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/usr/share/webapps/bookstack/storage/framework/views/91645b6b6196080a0a63b4cbf9174ea58199722f.php): failed to open stream: Read-only file system in /usr/share/webapps/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133
Mär 19 12:52:02 amaury-pc nginx[5191]: Stack trace:
Mär 19 12:52:02 amaury-pc nginx[5191]: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
Mär 19 12:52:02 amaury-pc nginx[5191]: #1 /usr/share/webapps/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents()
Mär 19 12:52:02 amaury-pc nginx[5191]: #2 /usr/share/webapps/bookstack/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(129): Illuminate\Filesystem\Filesystem->put()
Mär 19 12:52:02 amaury-pc nginx[5191]: #3 /usr/share/webapps/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile()
Mär 19 12:52:02 amaury-pc nginx[5191]: #4 /usr/share/webapps/bookstack/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\View\Engines\CompilerEngine->get()
Mär 19 12:52:02 amaury-pc nginx[5191]: #5 /usr/shar...PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/usr/share/webapps/bookstack/storage/framework/views/91645b6b6196080a0a63b4cbf9174ea58199722f.php): failed to open stream: Read-only file system in /usr/share/webapps/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133
Mär 19 12:52:02 amaury-pc nginx[5191]: Stack trace:
Mär 19 12:52:02 amaury-pc nginx[5191]: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
Mär 19 12:52:02 amaury-pc nginx[5191]: #1 /usr/share/webapps/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents()
Mär 19 12:52:02 amaury-pc nginx[5191]: #2 /usr/share/webapps/bookstack/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(129): Illuminate\Filesystem\Filesystem->put()
Mär 19 12:52:02 amaury-pc nginx[5191]: #3 /usr/share/webapps/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile()
Mär 19 12:52:02 amaury-pc nginx[5191]: #4 /usr/share/webapps/bookstack/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate
```
I have been wondering why it is looking for an inexistent file in the views folder, until I noticed that switching to php 7.3 solves the issue. 
The whole bookstack folder is recursively owned and writable by the http user.

 - Exact BookStack Version (Found in settings): 0.28.3
 - PHP Version: 7.4.3
 - Hosting Method (Nginx/Apache/Docker): nginx with php 7.4

I did a few diffs to see if it could be a configuration issue:
```
diff /etc/php/php.ini /etc/php73/php.ini 
759c759
< extension_dir = "/usr/lib/php/modules/"
---
> extension_dir = "/usr/lib/php73/modules/"
```
```
diff /etc/php/php-fpm.conf /etc/php73/php-fpm.conf 
17c17
< ;pid = /run/php-fpm/php-fpm.pid
---
> ;pid = /run/php73-fpm/php-fpm.pid
143c143
< include=/etc/php/php-fpm.d/*.conf
---
> include=/etc/php73/php-fpm.d/*.conf
```
The following are the only files in the php(73)-fpm.d/ folder
```
diff /etc/php/php-fpm.d/www.conf /etc/php73/php-fpm.d/www.conf 
36c36
< listen = /run/php-fpm/php-fpm.sock
---
> listen = /run/php73-fpm/php-fpm.sock
117c117
< ; Default Value: (min_spare_servers + max_spare_servers) / 2
---
> ; Default Value: min_spare_servers + (max_spare_servers - min_spare_servers) / 2
232c232
< ;       It's available in: /usr/share/php/fpm/status.html
---
> ;       It's available in: /usr/share/php73/fpm/status.html
```

Any help is greatly appreciated. 
I am currently trying to submit bookstack to the Arch User Repositories and make it easy to install, run and update it in archlinux and derivatives.

**Comment by amo13** [comment]
the diff between `php -m` and `php73 -m` only gives
```
25c25
< pdo_sqlite
---
> pdo_sqlsrv
33d32
< sqlite3
```
All required modules seem to be loaded correctly for both php (7.4) and php73.

**Comment by MikeyMJCO** [comment]
When you switch to PHP7.4 can you run a `php artisan view:clear` and `php artisan config:clear`

**Comment by amo13** [comment]
I did, but no difference...
```
amo@amaury-pc bookstack]$ sudo -u http php artisan view:clear
Compiled views cleared!
[amo@amaury-pc bookstack]$ sudo -u http php artisan config:clear
Configuration cache cleared!
[amo@amaury-pc bookstack]$ curl http://localhost
[amo@amaury-pc bookstack]$ 
```
Thank you for your help investigating this

**Comment by MikeyMJCO** [comment]
I'll try and get an archlinux VM up and running tomorrow and do some deeper investigation. I can confirm that PHP7.4 FPM on Ubuntu 18.04/20.04 and Debian Buster both work!

**Comment by amo13** [comment]
Awesome!
Let me know if I can help with anything, provide logs or try something else.

**Comment by MikeyMJCO** [comment]
Will do - let me do a reproduction test first on this - if that fails then at least I have an also-broken environment for debugging this!

**Comment by amo13** [comment]
I have never setup or used any virtual machine and I don't know if it is painful to get an arch virtual machine started. If it is, another idea which comes to my mind is to just temporarily boot an [ISO of manjaro](https://manjaro.org/download/). Manjaro does not really differ from arch but only adds convenience stuff on top of it. I use it on my PC (server is still arch) and I have the exact same issue with bookstack and php 7.4. So maybe this is faster and more convenient to reproduce the issue

**Comment by ssddanbrown** [comment]
Just given this a go on a Manjaro VM. Used standard package manager components. PHP version details:

```
[dan-standardpcq35ich92009 bookstack]# php -v
PHP 7.4.3 (cli) (built: Feb 18 2020 15:35:13) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

Instance running fine without the above issue. Used the same nginx config. Did install into a `/srv/http` directory though. 

@amo13 Could you post the result of 

```bash
ls -alh /usr/share/webapps/bookstack/storage/framework/views/
```

and also:

```bash
ps aux | grep php-fpm
```

**Comment by amo13** [comment]
Oh, this is odd....

Ok, I have:
```
[amo@server ~]$ ls -alh /usr/share/webapps/bookstack/storage/framework/views/
total 288K
drwxr-xr-x 1 http http 5.0K Apr  1 17:29 .
drwxr-xr-x 1 http http   56 Mar 12 12:22 ..
-rw-r--r-- 1 http http  449 Mar 28 14:11 00a44915c847761a8606da5c8344adfea5198920.php
-rw-r--r-- 1 http http  783 Mar 28 14:11 01d14ea2a98e4548a819346da897125485592db0.php
-rw-r--r-- 1 http http  928 Mar 28 14:11 039a74e4969eb27640095de044def94451a12c82.php
-rw-r--r-- 1 http http  14K Mar 30 13:31 0609fb857867944c439cae9153a7ce9e284487e5.php
-rw-r--r-- 1 http http 2.0K Mar 28 14:11 0bd1dd9aed686c08659a29391829dbdd636cfede.php
-rw-r--r-- 1 http http 1.1K Mar 28 14:11 1a0c7859f752dd9003c2082e260aa6eb72367731.php
-rw-r--r-- 1 http http  637 Mar 28 14:11 1bbef97f9bc797f6e429d18758ab93caa88e3875.php
-rw-r--r-- 1 http http  831 Mar 28 14:11 22067c2152cc085c5e4d6f1ffb45dac06a945f53.php
-rw-r--r-- 1 http http 1.8K Mar 28 14:11 228f427ffacbbbe2154d6255129b660389df1c67.php
-rw-r--r-- 1 http http 1.4K Mar 28 14:11 22c1e1e7828253252e131f3e95165bc199a56743.php
-rw-r--r-- 1 http http 1.4K Mar 28 14:11 2c8e5df16b50d2e2ac3f82abd174a9eaff9d5cbd.php
-rw-r--r-- 1 http http  991 Mar 28 14:11 2ed143293b8d927428311158b20bb4f7043ffac1.php
-rw-r--r-- 1 http http 3.2K Mar 28 14:11 2fff5c77467f39a31b62ed730617aae1ab3daf68.php
-rw-r--r-- 1 http http  19K Mar 28 14:11 33157a40fc4f9f1a0ce1feea34dac7dce313e7f4.php
-rw-r--r-- 1 http http 1.6K Mar 28 14:11 4d35b66640ebada3a9bf680c46987a8c19e5ce9b.php
-rw-r--r-- 1 http http 6.7K Mar 28 14:11 4f5232ac8c6f2efeb18df381f53b94339b79c2c0.php
-rw-r--r-- 1 http http  504 Mar 28 14:11 545012a6200880552c51d26cb9237e6ba4ec3f5b.php
-rw-r--r-- 1 http http 2.6K Mar 28 14:11 57924880c665f71f58d94cd0be04173a9f9b4a34.php
-rw-r--r-- 1 http http  286 Mar 28 14:11 5fc7340125b522fea29cb1bb0d7232b2b7f86981.php
-rw-r--r-- 1 http http 1.2K Mar 28 14:11 63fb0419b0afb6c4545823f0d68927d12df7e47f.php
-rw-r--r-- 1 http http 8.8K Mar 28 14:11 7b48915ec3e3a84e0e71e4de86cd7fa1f015cb93.php
-rw-r--r-- 1 http http 2.3K Mar 28 14:11 807e9d346424ebf9e3c43655eed3016946396775.php
-rw-r--r-- 1 http http 2.7K Mar 29 13:07 809796f0bdcda7f8aec0273c1c5532da9660e09f.php
-rw-r--r-- 1 http http 1.2K Mar 28 14:11 8bbccd049ea088770e9f8cc7e181a1c8bc6f8b68.php
-rw-r--r-- 1 http http 1.8K Mar 28 14:11 8c2d9b14e31146f93579d9a5003277193bd49945.php
-rw-r--r-- 1 http http 1.1K Mar 28 14:11 93ffcf993426488139ce33989e909e1791928066.php
-rw-r--r-- 1 http http 1.1K Mar 28 14:11 96e04a871bd02c108258fcd00eebd9581789bd3d.php
-rw-r--r-- 1 http http 1.7K Mar 28 14:11 9eb5e72afa139c6bf7fd6b61ce9dd3035cfc425b.php
-rw-r--r-- 1 http http  722 Mar 28 14:11 9f621e9d0630e141b88d0ebc3cee33ee3f4a7cea.php
-rw-r--r-- 1 http http 1.2K Mar 28 14:11 a151b776cb469b7ab7ae8a2a5eb752e399991b24.php
-rw-r--r-- 1 http http  848 Mar 28 14:11 a2a33b011b82383cd829e73767fd82736756f7a6.php
-rw-r--r-- 1 http http 2.2K Mar 28 14:11 a7885379454503c1cda03306a80d7a18066e5b77.php
-rw-r--r-- 1 http http 1.7K Mar 28 14:11 aa1efe665a23e88f4be5546853538e0521ccc538.php
-rw-r--r-- 1 http http  821 Mar 28 14:11 af8c1eb82c50668bb3f2017523cd6a425bac9840.php
-rw-r--r-- 1 http http 2.8K Mar 28 14:11 b1ff61236f9e760bb2585f273cf0c06431bd00d4.php
-rw-r--r-- 1 http http 2.2K Mar 28 14:11 b211df4138a8abd2decd92327ddc2147c640421c.php
-rw-r--r-- 1 http http  359 Mar 28 14:11 b34f95a8823098b73f4fa46cb92993eb0d527c68.php
-rw-r--r-- 1 http http 1.1K Mar 28 14:11 b3ba0fdfe45aef3fff4dfd76d17dc737c92363d8.php
-rw-r--r-- 1 http http 1.2K Mar 28 14:11 c15486c579fe456d570004f0e72f12d668884a98.php
-rw-r--r-- 1 http http  830 Mar 28 14:11 c78c8778417360a67bf4f757eceeb7dabca86787.php
-rw-r--r-- 1 http http 2.8K Mar 28 14:11 c893f4e81f9ee4912d8bbc4ee1bfcb80e2795a93.php
-rw-r--r-- 1 http http 2.1K Mar 28 14:11 c89903855deb202d49244817ec567b45ed29b039.php
-rw-r--r-- 1 http http  760 Mar 28 14:11 cdc7dd1f924a58db9cf6e8f2307cb1e4149b4238.php
-rw-r--r-- 1 http http 1010 Mar 28 14:11 d172511c9713b7dfa9af3100b85a2fc150f6bfb2.php
-rw-r--r-- 1 http http  916 Mar 28 14:11 d31981b3698efc171353ddd35193dc181623b00d.php
-rw-r--r-- 1 http http  321 Mar 28 14:11 d54720ec25e4f8393892d6470c8f10f20657c389.php
-rw-r--r-- 1 http http 1.4K Mar 28 14:11 d6e1dc308699e78a303823882c0219727d1139f7.php
-rw-r--r-- 1 http http 5.4K Mar 28 14:11 d7446c97b6b976755c26d5fce606264ab22e1120.php
-rw-r--r-- 1 http http 1.8K Mar 28 14:11 dc877fdc89b679196cfed831889970a328cb3a3f.php
-rw-r--r-- 1 http http  825 Mar 28 14:11 dc96f683f03991b5910e98a04279c10fe7c3dabd.php
-rw-r--r-- 1 http http 2.2K Mar 28 14:11 e2923d70bf5596695df457744507e341df34a88b.php
-rw-r--r-- 1 http http  189 Apr  1 17:29 e854180aec3709faf6fd7004aef399c27d5157e2.php
-rw-r--r-- 1 http http  689 Mar 29 19:32 f0247c0f5893996825be1aee8f145111c5c3290b.php
-rw-r--r-- 1 http http  842 Mar 28 14:11 f386b577991497843e10d9713dd2a760910b70f9.php
-rw-r--r-- 1 http http 7.5K Mar 28 14:11 f8f9ef6d680cabfb499ca35380f909c9858090d3.php
-rw-r--r-- 1 http http 5.2K Mar 28 14:11 fa6861690014f52e81382191714d149b5909398b.php
-rw-r--r-- 1 http http 7.0K Mar 28 14:11 fc85f3e9082d83e4a91f6a9eeec8ddc8e439f0d5.php
-rwxr-xr-x 1 http http   14 Mar 12 12:22 .gitignore
```
and:
```
[amo@server ~]$ ps aux | grep php-fpm
root     1164205  0.0  0.0 250000  1408 ?        Ss   Mar20   1:05 php-fpm: master process (/etc/php/php-fpm.conf)
http     1275566  0.1  2.7 349716 155696 ?       S    Mar24  16:00 php-fpm: pool www
http     1275577  0.1  2.6 350412 153620 ?       S    Mar24  16:25 php-fpm: pool www
http     1275578  0.1  2.7 348276 156256 ?       S    Mar24  16:11 php-fpm: pool www
http     1275589  0.1  2.8 347988 161060 ?       S    Mar24  16:10 php-fpm: pool www
http     1275590  0.1  2.7 350132 157584 ?       S    Mar24  16:22 php-fpm: pool www
http     1275603  0.1  2.6 347124 151772 ?       S    Mar24  16:02 php-fpm: pool www
http     1275604  0.1  2.6 347344 154052 ?       S    Mar24  16:06 php-fpm: pool www
http     1275618  0.1  2.7 349820 160096 ?       S    Mar24  17:07 php-fpm: pool www
http     1275619  0.1  2.6 347300 154032 ?       S    Mar24  16:36 php-fpm: pool www
http     1275635  0.1  2.7 350904 156160 ?       S    Mar24  16:08 php-fpm: pool www
http     1275636  0.1  2.6 349828 154928 ?       S    Mar24  16:32 php-fpm: pool www
http     1297129  0.1  2.6 346952 153488 ?       S    Mar25  14:26 php-fpm: pool www
http     1307678  0.1  2.6 347212 153352 ?       S    Mar26  12:51 php-fpm: pool www
http     1308524  0.1  2.7 350660 160296 ?       S    Mar26  13:10 php-fpm: pool www
http     1320235  0.1  2.6 348988 152252 ?       S    Mar26  12:02 php-fpm: pool www
http     1320667  0.1  2.7 346620 155080 ?       S    Mar26  12:05 php-fpm: pool www
amo      1477008  0.0  0.0   6284  2272 pts/0    S+   10:10   0:00 grep php-fpm
```

Thank you for your help with this! It's very appreciated.

**Comment by ssddanbrown** [comment]
:thinking: Hmm, All looks okay.

Do you perhaps have SELinux or AppArmour installed or anything similar @amo13?

**Comment by amo13** [comment]
Neither of those. I also do not know what similar thing I could have installed. The only "security" thing I use is fail2ban, but I doubt that it is interfering...
This is very odd. I had the exact same problem on my manjaro desktop, but I don't see why you were not able to reproduce this.
I am now trying to reproduce it myself once more on another manjaro system. I follow the guide for a manual installation, but now unfortunately, at the step `(sudo -u http) php artisan key:generate`, I get:
```
PHP Warning:  require(/home/amo/bookstacktest/BookStack/bootstrap/init.php): failed to open stream: Permission denied in /home/amo/bookstacktest/BookStack/artisan on line 16
PHP Fatal error:  require(): Failed opening required '/home/amo/bookstacktest/BookStack/bootstrap/init.php' (include_path='.:') in /home/amo/bookstacktest/BookStack/artisan on line 16
```
The BookStack folder is recursively owned by http:http and neither php-fpm nor mariadb show any error in the journal.

**Comment by amo13** [comment]
The denied permission hints that something is wrong with permission or ownership, but:
```
[amo@bodet-pc BookStack]$ ls -la
total 580
drwxr-xr-x 1 http http    590  4. Apr 00:47 .
drwxr-xr-x 1 amo  amo      18  4. Apr 00:45 ..
drwxr-xr-x 1 http http    300  4. Apr 00:46 app
-rwxr-xr-x 1 http http   1528  4. Apr 00:46 artisan
drwxr-xr-x 1 http http     40  4. Apr 00:46 bootstrap
-rw-r--r-- 1 http http   3432  4. Apr 00:46 composer.json
-rw-r--r-- 1 http http 279376  4. Apr 00:46 composer.lock
-rw-r--r-- 1 http http    200  4. Apr 00:46 crowdin.yml
drwxr-xr-x 1 http http     68  4. Apr 00:46 database
drwxr-xr-x 1 http http     18  4. Apr 00:46 dev
-rw-r--r-- 1 http http   1091  4. Apr 00:46 docker-compose.yml
-rw-r--r-- 1 http http    888  4. Apr 00:47 .env
-rw-r--r-- 1 http http    904  4. Apr 00:46 .env.example
-rw-r--r-- 1 http http   7799  4. Apr 00:46 .env.example.complete
drwxr-xr-x 1 http http    138  4. Apr 00:46 .git
-rw-r--r-- 1 http http     61  4. Apr 00:46 .gitattributes
drwxr-xr-x 1 http http    112  4. Apr 00:46 .github
-rw-r--r-- 1 http http    351  4. Apr 00:46 .gitignore
-rw-r--r-- 1 http http   1177  4. Apr 00:46 LICENSE
-rw-r--r-- 1 http http   1097  4. Apr 00:46 package.json
-rw-r--r-- 1 http http 222357  4. Apr 00:46 package-lock.json
-rw-r--r-- 1 http http    251  4. Apr 00:46 phpcs.xml
-rw-r--r-- 1 http http   2451  4. Apr 00:46 phpunit.xml
drwxr-xr-x 1 http http    220  4. Apr 00:46 public
-rw-r--r-- 1 http http  13430  4. Apr 00:46 readme.md
drwxr-xr-x 1 http http     40  4. Apr 00:46 resources
drwxr-xr-x 1 http http     28  4. Apr 00:46 routes
-rw-r--r-- 1 http http    567  4. Apr 00:46 server.php
drwxr-xr-x 1 http http     56  4. Apr 00:46 storage
drwxr-xr-x 1 http http    568  4. Apr 00:46 tests
drwxr-xr-x 1 http http     20  4. Apr 00:46 themes
-rw-r--r-- 1 http http      8  4. Apr 00:46 version
-rw-r--r-- 1 http http   1365  4. Apr 00:46 webpack.config.js
[amo@bodet-pc BookStack]$ ls -la bootstrap/
total 8
drwxr-xr-x 1 http http   40  4. Apr 00:46 .
drwxr-xr-x 1 http http  590  4. Apr 00:47 ..
-rw-r--r-- 1 http http 1600  4. Apr 00:46 app.php
drwxr-xr-x 1 http http   20  4. Apr 00:46 cache
-rw-r--r-- 1 http http  866  4. Apr 00:46 init.php
```

**Comment by ssddanbrown** [comment]
@amo13 On your desktop setup, If you give permission back to yourself, for all files & folders, then start BookStack directly through `php artisan serve`, does that have any issues?

**Comment by amo13** [comment]
yes, it gives:
```
PHP Warning:  require(/home/amo/bookstacktest/BookStack/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /home/amo/bookstacktest/BookStack/bootstrap/init.php on line 25
PHP Fatal error:  require(): Failed opening required '/home/amo/bookstacktest/BookStack/bootstrap/../vendor/autoload.php' (include_path='.:') in /home/amo/bookstacktest/BookStack/bootstrap/init.php on line 25
```

**Comment by amo13** [comment]
I reproduced the issue once again and I am beginning to think that there must be black magic involved in this... 
When I install to /srv/http/ (as you did in your Manjaro VM), every works just fine, but when I install to /usr/share/webapps/, then I get the white page. Same when I install to /home/amo/, even though I did `chown http:http` to the *parent* folder before cloning bookstack and I did every single install step as the http user in all cases. 
This is so odd...
I am not yet giving up on this, since I am determined to package bookstack for archlinux and derivatives, but the correct install location on archlinux would definitely be the unfunctional /usr/share/webapps location.
So, as a follow-up for this issue, I am [asking](https://bbs.archlinux.org/viewtopic.php?pid=1896929) the archlinux community for help on this

**Comment by ssddanbrown** [comment]
@amo13 Cool, I'm sure the arch community will be able to find the reason for this.

One extra thing I did think of, Maybe this is due to systemd sandboxing options. Having a look at the default unit files in my manjaro vm, such as the php one at `/usr/lib/systemd/system/php-fpm.service`, it does seem there are a lot of security/sandboxing options are enabled, at least when compared to my Ubuntu desktop equivalent. Unfortunately that wouldn't explain why you still had issues when running via `php artisan serve` since that should not be going through a systemd service.

**Comment by amo13** [comment]
Coincidence makes that somebody else had the same ambition than I had at pretty much the same time, but was more knowlegable and more successful than I was. BookStack is now easily installable on archlinux and derivatives as it can be found in the AUR (arch user repositories).
Installation now boils down to `yay -S bookstack`
Thank you a lot for your help on this thread!

**Comment by ssddanbrown** [comment]
@amo13 No problem! Thanks for trying so hard to get it packaged!
