### ISSUE TITLE
Unable to upload images

### ISSUE THREAD

**Issue by killadelphia** [BookStackApp/BookStack#2458]
Getting "An error occurred uploading the image" when trying to paste or upload images. I updated to 0.31.0 yesterday and it caused me some issues involving the artisan migration. I had to drop a couple of tables in order to get Bookstack working again (I was getting HTTP error 500). Once the migration completed everything seemed to be working and intact but I am unable to upload any images.

Here is the error I am getting in laravel.log:

> production.ERROR: Method Illuminate\Validation\Validator::validateImageExtension does not exist. {"userId":1,"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Validation\\Validator::validate$[stacktrace]

And here is the ls -l for my storage folder:

> drwxrwxrwx  7 www-data www-data     4096 Feb 10  2020 storage

Thanks in advance for any assistance.

**Comment by ssddanbrown** [comment]
Hi @killadelphia,
Do you get any errors when running the `composer install` step of the update commands?

Additionally, could you post the output of running `git status` within the bookstack install directory?

**Comment by jsreynolds** [comment]
Whew. Fought this for a while myself to no avail. Here is my git status:

```
On branch release
Your branch is up to date with 'origin/release'.
nothing to commit, working tree clean
```

Here is the log:

```
[2021-01-08 16:17:53] production.ERROR: Method Illuminate\Validation\Validator::validateImageExtension does not exist. {"userId":2,"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Validation\\Validator::validateImageExtension does not exist. at /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Validation/Validator.php:1308)
[stacktrace]
#0 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(469): Illuminate\\Validation\\Validator->__call()
#1 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(311): Illuminate\\Validation\\Validator->validateAttribute()
#2 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(342): Illuminate\\Validation\\Validator->passes()
#3 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Validation/Validator.php(385): Illuminate\\Validation\\Validator->fails()
#4 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Validation/ValidatesRequests.php(47): Illuminate\\Validation\\Validator->validate()
#5 /home/jreynolds/www/bookstack/app/Http/Controllers/UserController.php(148): BookStack\\Http\\Controllers\\Controller->validate()
#6 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): BookStack\\Http\\Controllers\\UserController->update()
#7 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#8 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#9 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#10 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Routing\\Route->run()
#11 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#12 /home/jreynolds/www/bookstack/app/Http/Middleware/Authenticate.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\\Http\\Middleware\\Authenticate->handle()
#14 /home/jreynolds/www/bookstack/app/Http/Middleware/GlobalViewData.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\\Http\\Middleware\\GlobalViewData->handle()
#16 /home/jreynolds/www/bookstack/app/Http/Middleware/Localization.php(76): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\\Http\\Middleware\\Localization->handle()
#18 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#20 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#22 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#24 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#26 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#28 /home/jreynolds/www/bookstack/app/Http/Middleware/ControlIframeSecurity.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\\Http\\Middleware\\ControlIframeSecurity->handle()
#30 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#32 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#33 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#34 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#35 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#36 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#37 /home/jreynolds/www/bookstack/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/jreynolds/www/bookstack/app/Http/Middleware/TrustProxies.php(39): Fideloper\\Proxy\\TrustProxies->handle()
#39 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): BookStack\\Http\\Middleware\\TrustProxies->handle()
#40 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#42 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#44 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#46 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#48 /home/jreynolds/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#49 /home/jreynolds/www/bookstack/public/index.php(56): Illuminate\\Foundation\\Http\\Kernel->handle()
#50 {main}
"} 

```

**Comment by killadelphia** [comment]
Thanks for the quick reply Dan, it's been a busy couple of days for me. Here is the output for `composer install`

`
matt@nucserver:/var/www/bookstack$ composer install
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: barryvdh/laravel-dompdf
Discovered Package: barryvdh/laravel-ide-helper
Discovered Package: barryvdh/laravel-snappy
Discovered Package: facade/ignition
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/socialite
Discovered Package: laravel/tinker
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: socialiteproviders/manager
Package manifest generated successfully.
> @php artisan cache:clear
Failed to clear cache. Make sure you have the appropriate permissions.
> @php artisan view:clear
Compiled views cleared!
`

and here is the output from `git status`

`
matt@nucserver:/var/www/bookstack$ git status
On branch release
Your branch is up to date with 'origin/release'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   composer.json
        modified:   composer.lock

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .env.bak
        bookstack-files-backup.tar.gz
        composer.phar

no changes added to commit (use "git add" and/or "git commit -a")
`

**Comment by ssddanbrown** [comment]
@jsreynolds @killadelphia Thanks for confirming both.

Could you check if you have a `bootstrap/cache/config.php` file within your BookStack install? If you do, delete this. Let me know if you did and if that fixes things if it did exist.

**Comment by jsreynolds** [comment]
@ssddanbrown 

Hello, I had the config.php file, and I deleted it, rebooted, tried changing an image again in the user area (which was what was failing for me) and now it works.

Thank you!

**Comment by killadelphia** [comment]
@ssddanbrown I did have the config.php file. I removed it and updated to 0.31.3 and now uploading images is working correctly again. Thanks!

**Comment by ssddanbrown** [comment]
@jsreynolds @killadelphia Ah great, thanks both for confirming. Means you might have ran `php artisan config:cache` or something similar at some point. That does improve performance but you do have to be aware to clear the caches on updates.
