### ISSUE TITLE
Error updating from v21.04.2 - v21.04.5

### ISSUE THREAD

**Issue by nousrfound** [BookStackApp/BookStack#2754]
**Describe the bug**
Getting an PHP fatal error when updating

I'm not sure how critical the error is, when open up Bookstack after the update it shows the new version and seems to work, but not sure if some things might not work.

Ubuntu 20.04.2 LTS
PHP8
Everything is updated as of the posting.

```
remote: Enumerating objects: 419, done.
remote: Counting objects: 100% (418/418), done.
remote: Compressing objects: 100% (223/223), done.
remote: Total 419 (delta 214), reused 302 (delta 190), pack-reused 1
Receiving objects: 100% (419/419), 283.52 KiB | 3.73 MiB/s, done.
Resolving deltas: 100% (214/214), completed with 63 local objects.
From https://github.com/BookStackApp/BookStack
 * branch              release    -> FETCH_HEAD
   6f4a6ab8..8eb98cd5  release    -> origin/release
Updating 6f4a6ab8..8eb98cd5
Fast-forward
 .env.example.complete                                               |    1 +
 .github/translators.txt                                             |    8 ++
 app/Actions/ViewService.php                                         |    1 +
 app/Config/dompdf.php                                               |    4 +-
 app/Config/saml2.php                                                |   10 ++
 app/Entities/Repos/PageRepo.php                                     |    2 +-
 app/Entities/Tools/PageContent.php                                  |   64 +----------
 app/Exceptions/Handler.php                                          |   48 --------
 app/Exceptions/NotifyException.php                                  |   21 +++-
 app/Exceptions/PrettyException.php                                  |   39 ++++++-
 app/Http/Controllers/HomeController.php                             |    2 +-
 app/Http/Controllers/Images/ImageController.php                     |    6 +-
 app/Http/Controllers/PageController.php                             |    3 -
 app/Uploads/ImageService.php                                        |   25 ++++-
 app/Util/HtmlContentFilter.php                                      |   71 ++++++++++++
 composer.lock                                                       |  347 +++++++++++++++++++++++++++++++++-----------------------
 database/migrations/2017_03_19_091553_create_search_index_table.php |    2 +-
 database/migrations/2018_07_15_173514_add_role_external_auth_id.php |    2 +-
 database/migrations/2018_08_04_115700_create_bookshelves_table.php  |    4 +-
 database/migrations/2021_03_08_215138_add_user_slug.php             |    2 +-
 package-lock.json                                                   | 1277 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 public/dist/export-styles.css                                       |    2 +-
 public/dist/styles.css                                              |    2 +-
 resources/lang/ar/activities.php                                    |    2 +-
 resources/lang/ar/auth.php                                          |    6 +-
 resources/lang/ar/common.php                                        |   22 ++--
 resources/lang/ar/components.php                                    |    2 +-
 resources/lang/ar/entities.php                                      |   52 ++++-----
 resources/lang/ar/errors.php                                        |    3 +
 resources/lang/bg/errors.php                                        |    3 +
 resources/lang/bs/errors.php                                        |    3 +
 resources/lang/ca/auth.php                                          |    6 +-
 resources/lang/ca/common.php                                        |    4 +-
 resources/lang/ca/errors.php                                        |    3 +
 resources/lang/ca/passwords.php                                     |    8 +-
 resources/lang/ca/validation.php                                    |    4 +-
 resources/lang/cs/errors.php                                        |    3 +
 resources/lang/da/errors.php                                        |    3 +
 resources/lang/de/common.php                                        |    8 +-
 resources/lang/de/entities.php                                      |    2 +-
 resources/lang/de/errors.php                                        |    3 +
 resources/lang/de/settings.php                                      |    4 +-
 resources/lang/de_informal/common.php                               |   10 +-
 resources/lang/de_informal/entities.php                             |    2 +-
 resources/lang/de_informal/errors.php                               |    3 +
 resources/lang/de_informal/settings.php                             |    6 +-
 resources/lang/en/errors.php                                        |    3 +
 resources/lang/es/errors.php                                        |    3 +
 resources/lang/es_AR/common.php                                     |    6 +-
 resources/lang/es_AR/entities.php                                   |    2 +-
 resources/lang/es_AR/errors.php                                     |    3 +
 resources/lang/fa/errors.php                                        |    3 +
 resources/lang/fr/common.php                                        |    6 +-
 resources/lang/fr/errors.php                                        |    3 +
 resources/lang/he/errors.php                                        |    3 +
 resources/lang/hu/errors.php                                        |    3 +
 resources/lang/id/common.php                                        |    6 +-
 resources/lang/id/errors.php                                        |    3 +
 resources/lang/it/activities.php                                    |    4 +-
 resources/lang/it/common.php                                        |   18 +--
 resources/lang/it/components.php                                    |    2 +-
 resources/lang/it/entities.php                                      |   12 +-
 resources/lang/it/errors.php                                        |   13 ++-
 resources/lang/it/passwords.php                                     |    4 +-
 resources/lang/it/settings.php                                      |   74 ++++++------
 resources/lang/it/validation.php                                    |    2 +-
 resources/lang/ja/errors.php                                        |    3 +
 resources/lang/ja/settings.php                                      |   36 +++---
 resources/lang/ko/activities.php                                    |    2 +-
 resources/lang/ko/common.php                                        |    8 +-
 resources/lang/ko/entities.php                                      |    4 +-
 resources/lang/ko/errors.php                                        |    3 +
 resources/lang/ko/settings.php                                      |   66 +++++------
 resources/lang/ko/validation.php                                    |    2 +-
 resources/lang/lv/common.php                                        |    6 +-
 resources/lang/lv/errors.php                                        |    3 +
 resources/lang/nb/errors.php                                        |    3 +
 resources/lang/nl/activities.php                                    |   42 +++----
 resources/lang/nl/auth.php                                          |   28 ++---
 resources/lang/nl/common.php                                        |   42 +++----
 resources/lang/nl/components.php                                    |   14 +--
 resources/lang/nl/entities.php                                      |   38 +++----
 resources/lang/nl/errors.php                                        |    3 +
 resources/lang/nl/settings.php                                      |  122 ++++++++++----------
 resources/lang/nl/validation.php                                    |    2 +-
 resources/lang/pl/errors.php                                        |    3 +
 resources/lang/pt/common.php                                        |    6 +-
 resources/lang/pt/errors.php                                        |    3 +
 resources/lang/pt_BR/errors.php                                     |    3 +
 resources/lang/ru/common.php                                        |    6 +-
 resources/lang/ru/errors.php                                        |    3 +
 resources/lang/sk/errors.php                                        |    3 +
 resources/lang/sl/errors.php                                        |    3 +
 resources/lang/sv/errors.php                                        |    3 +
 resources/lang/tr/errors.php                                        |    3 +
 resources/lang/uk/errors.php                                        |    3 +
 resources/lang/vi/errors.php                                        |    3 +
 resources/lang/zh_CN/errors.php                                     |    3 +
 resources/lang/zh_TW/errors.php                                     |    3 +
 resources/sass/_buttons.scss                                        |    1 +
 resources/sass/_forms.scss                                          |   10 ++
 resources/sass/_header.scss                                         |    7 +-
 resources/sass/_tables.scss                                         |    1 +
 resources/sass/export-styles.scss                                   |   24 +++-
 resources/views/auth/forms/login/saml2.blade.php                    |    2 +-
 resources/views/books/export.blade.php                              |   42 +------
 resources/views/chapters/export.blade.php                           |   34 +-----
 resources/views/errors/404.blade.php                                |    4 +-
 resources/views/export-layout.blade.php                             |   15 +++
 resources/views/pages/export.blade.php                              |   54 ++-------
 resources/views/partials/custom-head-content.blade.php              |    5 -
 resources/views/partials/custom-head.blade.php                      |    6 +-
 resources/views/partials/entity-export-meta.blade.php               |    4 +-
 resources/views/partials/export-custom-head.blade.php               |    5 +
 resources/views/partials/export-styles.blade.php                    |   21 ++++
 routes/web.php                                                      |    2 +-
 tests/Auth/Saml2Test.php                                            |   35 ++++++
 tests/Entity/ExportTest.php                                         |   33 ++++++
 tests/Entity/PageTest.php                                           |   23 ++++
 tests/ErrorTest.php                                                 |    7 ++
 tests/HomepageTest.php                                              |   13 +++
 tests/Unit/ConfigTest.php                                           |   13 ++-
 version                                                             |    2 +-
 123 files changed, 2353 insertions(+), 763 deletions(-)
 create mode 100644 app/Util/HtmlContentFilter.php
 create mode 100644 resources/views/export-layout.blade.php
 delete mode 100644 resources/views/partials/custom-head-content.blade.php
 create mode 100644 resources/views/partials/export-custom-head.blade.php
Deprecation Notice: Required parameter $path follows optional parameter $schema in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Required parameter $path follows optional parameter $schema in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:108
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:130
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
Loading composer repositories with package information
Installing dependencies from lock file
PHP Fatal error:  Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 /usr/share/php/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 /usr/share/php/Composer/DependencyResolver/Solver.php(740): Composer\DependencyResolver\Solver->selectAndInstall()
#4 /usr/share/php/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat()
#5 /usr/share/php/Composer/Installer.php(489): Composer\DependencyResolver\Solver->solve()
#6 /usr/share/php/Composer/Installer.php(232): Composer\Installer->doInstall()
#7 /usr/share/php/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
#8 /usr/share/php/Symfony/Component/Console/Command/Command.php(255): Composer\Command\InstallCommand->execute()
#9 /usr/share/php/Symfony/Component/Console/Application.php(934): Symfony\Component\Console\Command\Command->run()
#10 /usr/share/php/Symfony/Component/Console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /usr/share/php/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun()
#12 /usr/share/php/Symfony/Component/Console/Application.php(149): Composer\Console\Application->doRun()
#13 /usr/share/php/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run()
#14 /usr/bin/composer(62): Composer\Console\Application->run()
#15 {main}
  thrown in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php on line 84

Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 /usr/share/php/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 /usr/share/php/Composer/DependencyResolver/Solver.php(740): Composer\DependencyResolver\Solver->selectAndInstall()
#4 /usr/share/php/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat()
#5 /usr/share/php/Composer/Installer.php(489): Composer\DependencyResolver\Solver->solve()
#6 /usr/share/php/Composer/Installer.php(232): Composer\Installer->doInstall()
#7 /usr/share/php/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
#8 /usr/share/php/Symfony/Component/Console/Command/Command.php(255): Composer\Command\InstallCommand->execute()
#9 /usr/share/php/Symfony/Component/Console/Application.php(934): Symfony\Component\Console\Command\Command->run()
#10 /usr/share/php/Symfony/Component/Console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /usr/share/php/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun()
#12 /usr/share/php/Symfony/Component/Console/Application.php(149): Composer\Console\Application->doRun()
#13 /usr/share/php/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run()
#14 /usr/bin/composer(62): Composer\Console\Application->run()
#15 {main}
  thrown in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php on line 84
```

**Comment by ssddanbrown** [comment]
Hi @nousrfound,
I suspect the version of composer installed is the ubuntu-provided version and is no longer compatible with the version of PHP you have on that system.

You can remove this system-provided version and upgrade to the latest current composer version like so:

```bash
sudo apt remove composer
wget https://getcomposer.org/download/2.0.13/composer.phar
chmod +x composer.phar
sudo mv composer.phar /usr/local/bin/composer
```

**Comment by nousrfound** [comment]
Hi @ssddanbrown 
That was indeed the problem, no errors after updating.

Thank you for the quick reply.
