### ISSUE TITLE
Upgrade to v21.08.5

### ISSUE THREAD

**Issue by jacksonp2008** [BookStackApp/BookStack#2967]
**Describe the bug**
Current version is 0.26.2 running on Ubuntu 16.04, attempting to upgrade to latest.

**Steps To Reproduce**
1. Upgraded system to Ubuntu 18.04.6 LTS
2. Upgraded php to 7.4 (per Updating to v0.28 or higher)
3. Upgraded to php 8 (per Updating to v21.04 or higher)
4. Attempt upgrade with `git pull origin release && composer install --no-dev && php artisan migrate`

**Expected behavior**
Be great if it just worked.

**Screenshots**
Resulting error message:

```
pollock@ip-172-31-31-66:/var/www/bookstack$ composer install --no-dev
Deprecation Notice: Required parameter $path follows optional parameter $schema in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Required parameter $path follows optional parameter $schema in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:108
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:129
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:129
Cannot create cache directory /home/spollock/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/spollock/.composer/cache/files/, or directory is not writable. Proceeding without cache
> @php -r "!file_exists('bootstrap/cache/services.php') || @unlink('bootstrap/cache/services.php');"
Loading composer repositories with package information
Installing dependencies from lock file
PHP Fatal error:  Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 /usr/share/php/Composer/DependencyResolver/Solver.php(383): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 /usr/share/php/Composer/DependencyResolver/Solver.php(736): Composer\DependencyResolver\Solver->selectAndInstall()
#4 /usr/share/php/Composer/DependencyResolver/Solver.php(228): Composer\DependencyResolver\Solver->runSat()
#5 /usr/share/php/Composer/Installer.php(473): Composer\DependencyResolver\Solver->solve()
#6 /usr/share/php/Composer/Installer.php(227): Composer\Installer->doInstall()
#7 /usr/share/php/Composer/Command/InstallCommand.php(119): Composer\Installer->run()
#8 /usr/share/php/Symfony/Component/Console/Command/Command.php(252): Composer\Command\InstallCommand->execute()
#9 /usr/share/php/Symfony/Component/Console/Application.php(946): Symfony\Component\Console\Command\Command->run()
#10 /usr/share/php/Symfony/Component/Console/Application.php(248): Symfony\Component\Console\Application->doRunCommand()
#11 /usr/share/php/Composer/Console/Application.php(251): Symfony\Component\Console\Application->doRun()
#12 /usr/share/php/Symfony/Component/Console/Application.php(148): Composer\Console\Application->doRun()
#13 /usr/share/php/Composer/Console/Application.php(100): Symfony\Component\Console\Application->run()
#14 /usr/bin/composer(59): Composer\Console\Application->run()
#15 {main}
  thrown in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php on line 84

Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 /usr/share/php/Composer/DependencyResolver/Solver.php(383): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 /usr/share/php/Composer/DependencyResolver/Solver.php(736): Composer\DependencyResolver\Solver->selectAndInstall()
#4 /usr/share/php/Composer/DependencyResolver/Solver.php(228): Composer\DependencyResolver\Solver->runSat()
#5 /usr/share/php/Composer/Installer.php(473): Composer\DependencyResolver\Solver->solve()
#6 /usr/share/php/Composer/Installer.php(227): Composer\Installer->doInstall()
#7 /usr/share/php/Composer/Command/InstallCommand.php(119): Composer\Installer->run()
#8 /usr/share/php/Symfony/Component/Console/Command/Command.php(252): Composer\Command\InstallCommand->execute()
#9 /usr/share/php/Symfony/Component/Console/Application.php(946): Symfony\Component\Console\Command\Command->run()
#10 /usr/share/php/Symfony/Component/Console/Application.php(248): Symfony\Component\Console\Application->doRunCommand()
#11 /usr/share/php/Composer/Console/Application.php(251): Symfony\Component\Console\Application->doRun()
#12 /usr/share/php/Symfony/Component/Console/Application.php(148): Composer\Console\Application->doRun()
#13 /usr/share/php/Composer/Console/Application.php(100): Symfony\Component\Console\Application->run()
#14 /usr/bin/composer(59): Composer\Console\Application->run()
#15 {main}
  thrown in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php on line 84
```

**Your Configuration (please complete the following information):**
 - Exact BookStack Version (Found in settings): 0.26.2
 - PHP Version: PHP 8.0.11 (cli) (built: Sep 23 2021 21:26:06) ( NTS )
 - Hosting Method (Nginx/Apache/Docker): nginx

**Additional context**

**Comment by jacksonp2008** [comment]
Thanks Dan, the above worked well on one system.

On the second I did the same and am getting this error in the browser window:

```
Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0".
```

Yet I had already installed both php 7.4 and 8.0 per above steps.

```
root@ipsadfasf:/var/www/bookstack# php --version
PHP 8.0.11 (cli) (built: Sep 23 2021 21:26:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.11, Copyright (c), by Zend Technologies
```
