### ISSUE TITLE
Cannot delete an uploaded image from the Gallery

### ISSUE THREAD

**Issue by Maquert** [BookStackApp/BookStack#311]
* BookStack Version: 0.13.1
* PHP Version: 7.0.13
* MySQL Version: 14.14, Dist. 5.7.17
* OS: Ubuntu 16.0.

*Installed using the script.*

##### Expected Behaviour
With the Gallery open (by tapping on Insert Image when editing, for instance) I click on the Trash/Bin red button and the selected image is removed from the Gallery.

##### Actual Behaviour
The delete button does nothing. Instead, I get a bad request error (500) from the Debugger Console.
Only the Admin is able to delete images. Other roles are supposed to have permissions to do this as well.

It might no be important, but images are being stored on Amazon S3.

![pasted image at 2017_02_15 09_48](https://cloud.githubusercontent.com/assets/5532393/22966911/788249a8-f364-11e6-9e9d-638aa855e813.png)
![pasted image at 2017_02_15 09_49](https://cloud.githubusercontent.com/assets/5532393/22966912/78be8cec-f364-11e6-9b41-d2daafe67014.png)

I will provide further details if needed.

This is the error trace I'm getting from Laravel:

Exception:
```
Call to undefined method Illuminate\Database\Query\Builder::jointPermissions()
```

```
BadMethodCallException

        $className = static::class;

        throw new BadMethodCallException("Call to undefined method {$className}::{$method}()");
    }
}
```

Messages:
```
LOG.error: BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::jointPermissions() in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2440
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('jointPermission...', Array)
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1436): call_user_func_array(Array, Array)
#2 [internal function]: Illuminate\Database\Eloquent\Builder->__call('jointPermission...', Array)
#3 /var/www/bookstack/bootstrap/cache/compiled.php(11602): call_user_func_array(Array, Array)
#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1007): Illuminate\Database\Eloquent\Model->__call('jointPermission...', Array)
#5 [internal function]: Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}()
#6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(184): call_user_func(Object(Closure))
#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1008): Illuminate\Database\Eloquent\Relations\Relation::noConstraints(Object(Closure))
#8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(810): Illuminate\Database\Eloquent\Builder->getHasRelationQuery('jointPermission...')
#9 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(881): Illuminate\Database\Eloquent\Builder->has('jointPermission...', '>=', 1, 'and', Object(Closure))
#10 /var/www/bookstack/app/Services/PermissionService.php(458): Illuminate\Database\Eloquent\Builder->whereHas('jointPermission...', Object(Closure))
#11 [internal function]: BookStack\Services\PermissionService->BookStack\Services\{closure}(Object(Illuminate\Database\Eloquent\Builder))
#12 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(771): call_user_func(Object(Closure), Object(Illuminate\Database\Eloquent\Builder))
#13 /var/www/bookstack/app/Services/PermissionService.php(459): Illuminate\Database\Eloquent\Builder->where(Object(Closure))
#14 /var/www/bookstack/app/Services/PermissionService.php(415): BookStack\Services\PermissionService->entityRestrictionQuery(Object(Illuminate\Database\Eloquent\Builder))
#15 /var/www/bookstack/app/helpers.php(56): BookStack\Services\PermissionService->checkOwnableUserAccess(Object(BookStack\Image), 'image-delete')
#16 /var/www/bookstack/app/Http/Controllers/Controller.php(103): userCan('image-delete', Object(BookStack\Image))
#17 /var/www/bookstack/app/Http/Controllers/ImageController.php(160): BookStack\Http\Controllers\Controller->checkOwnablePermission('image-delete', Object(BookStack\Image))
#18 [internal function]: BookStack\Http\Controllers\ImageController->destroy(Object(BookStack\Repos\PageRepo), Object(Illuminate\Http\Request), '56')
#19 /var/www/bookstack/bootstrap/cache/compiled.php(9385): call_user_func_array(Array, Array)
#20 /var/www/bookstack/bootstrap/cache/compiled.php(9412): Illuminate\Routing\Controller->callAction('destroy', Array)
#21 /var/www/bookstack/bootstrap/cache/compiled.php(8470): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(BookStack\Http\Controllers\ImageController), 'destroy')
#22 /var/www/bookstack/bootstrap/cache/compiled.php(8451): Illuminate\Routing\Route->runController()
#23 /var/www/bookstack/bootstrap/cache/compiled.php(8147): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#24 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/bookstack/app/Http/Controllers/Controller.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/bookstack/bootstrap/cache/compiled.php(9862): BookStack\Http\Controllers\Controller->BookStack\Http\Controllers\{closure}(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/bookstack/app/Http/Middleware/Authenticate.php(47): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/bookstack/bootstrap/cache/compiled.php(9870): BookStack\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/bookstack/bootstrap/cache/compiled.php(9978): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/bookstack/bootstrap/cache/compiled.php(9870): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/bookstack/bootstrap/cache/compiled.php(3151): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/bookstack/bootstrap/cache/compiled.php(9870): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/bookstack/bootstrap/cache/compiled.php(13464): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/bookstack/bootstrap/cache/compiled.php(9870): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/bookstack/bootstrap/cache/compiled.php(11907): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/bookstack/bootstrap/cache/compiled.php(9870): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /var/www/bookstack/bootstrap/cache/compiled.php(13210): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/bookstack/bootstrap/cache/compiled.php(9870): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/bookstack/bootstrap/cache/compiled.php(13147): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/bookstack/bootstrap/cache/compiled.php(9870): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/bookstack/bootstrap/cache/compiled.php(9855): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/bookstack/bootstrap/cache/compiled.php(8148): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /var/www/bookstack/bootstrap/cache/compiled.php(8139): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#52 /var/www/bookstack/bootstrap/cache/compiled.php(8130): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#53 /var/www/bookstack/bootstrap/cache/compiled.php(2472): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#54 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/bookstack/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /var/www/bookstack/bootstrap/cache/compiled.php(9870): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /var/www/bookstack/bootstrap/cache/compiled.php(3213): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /var/www/bookstack/bootstrap/cache/compiled.php(9870): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/bookstack/bootstrap/cache/compiled.php(9855): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /var/www/bookstack/bootstrap/cache/compiled.php(2416): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#63 /var/www/bookstack/bootstrap/cache/compiled.php(2400): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#64 /var/www/bookstack/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#65 {main}
error
log
```

**Comment by ssddanbrown** [comment]
Hi @Maquert, Sorry for my late reply. I believe this was fixed in a more recent version of BookStack. Could you try updating and see if the issue persists?

**Comment by ssddanbrown** [comment]
Due to duration since last response I will close this issue. Feel free to continue to comment as it can always be re-opened if required.
