### ISSUE TITLE
Export PDF error

### ISSUE THREAD

**Issue by Statium** [BookStackApp/BookStack#3322]
### Describe the Bug

When exporting PDF, an error occurs (intermittently). Clearing the application cache helps (temporarily).
The problem occurs for all users. 

The problem is solved by the following commands:
php artisan cache:clear
php artisan config:cache
php artisan view:clear
php artisan bookstack:regenerate-search

### Steps to Reproduce

Export PDF random page

### Expected Behaviour

Export PDF file

### Screenshots or Additional Context

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/4026090/157856836-c516fca9-87d3-43a8-a100-b17ffee4a6ee.png)

</details>

<details>
<summary>Log Content</summary>

```
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'touch(): Unable...', 'C:\\xampp\\htdocs...', 1177, Array)
#1 C:\xampp\htdocs\vendor\dompdf\dompdf\lib\Cpdf.php(1177): touch('C:\\Users\\57F8~1...')
#2 C:\xampp\htdocs\vendor\dompdf\dompdf\lib\Cpdf.php(932): Dompdf\Cpdf->processFont(8, Array)
#3 C:\xampp\htdocs\vendor\dompdf\dompdf\lib\Cpdf.php(3196): Dompdf\Cpdf->o_font(8, 'add')
#4 C:\xampp\htdocs\vendor\dompdf\dompdf\src\Adapter\CPDF.php(1210): Dompdf\Cpdf->output(false)
#5 C:\xampp\htdocs\vendor\dompdf\dompdf\src\Dompdf.php(954): Dompdf\Adapter\CPDF->output(Array)
#6 C:\xampp\htdocs\vendor\barryvdh\laravel-dompdf\src\PDF.php(157): Dompdf\Dompdf->output()
#7 C:\xampp\htdocs\app\Entities\Tools\PdfGenerator.php(24): Barryvdh\DomPDF\PDF->output()
#8 C:\xampp\htdocs\app\Entities\Tools\ExportFormatter.php(148): BookStack\Entities\Tools\PdfGenerator->fromHtml('<!DOCTYPE html>...')
#9 C:\xampp\htdocs\app\Entities\Tools\ExportFormatter.php(97): BookStack\Entities\Tools\ExportFormatter->htmlToPdf('<!DOCTYPE html>...')
#10 C:\xampp\htdocs\app\Http\Controllers\PageExportController.php(37): BookStack\Entities\Tools\ExportFormatter->pageToPdf(Object(BookStack\Entities\Models\Page))
#11 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): BookStack\Http\Controllers\PageExportController->pdf('informatsiya', 'pravila-formiro...')
#12 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('pdf', Array)
#13 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Route.php(262): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(BookStack\Http\Controllers\PageExportController), 'pdf')
#14 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Route.php(205): Illuminate\Routing\Route->runController()
#15 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(695): Illuminate\Routing\Route->run()
#16 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(BookStack\Http\Request))
#17 C:\xampp\htdocs\app\Http\Middleware\CheckUserHasPermission.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#18 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): BookStack\Http\Middleware\CheckUserHasPermission->handle(Object(BookStack\Http\Request), Object(Closure), 'content-export')
#19 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#20 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): BookStack\Http\Middleware\Authenticate->handle(Object(BookStack\Http\Request), Object(Closure))
#21 C:\xampp\htdocs\app\Http\Middleware\Localization.php(82): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#22 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): BookStack\Http\Middleware\Localization->handle(Object(BookStack\Http\Request), Object(Closure))
#23 C:\xampp\htdocs\app\Http\Middleware\RunThemeActions.php(26): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#24 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): BookStack\Http\Middleware\RunThemeActions->handle(Object(BookStack\Http\Request), Object(Closure))
#25 C:\xampp\htdocs\app\Http\Middleware\CheckEmailConfirmed.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#26 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): BookStack\Http\Middleware\CheckEmailConfirmed->handle(Object(BookStack\Http\Request), Object(Closure))
#27 C:\xampp\htdocs\app\Http\Middleware\PreventAuthenticatedResponseCaching.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#28 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): BookStack\Http\Middleware\PreventAuthenticatedResponseCaching->handle(Object(BookStack\Http\Request), Object(Closure))
#29 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#30 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(BookStack\Http\Request), Object(Closure))
#31 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#32 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(BookStack\Http\Request), Object(Closure))
#33 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#34 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(BookStack\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#35 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(BookStack\Http\Request), Object(Closure))
#36 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#37 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(BookStack\Http\Request), Object(Closure))
#38 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#39 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(BookStack\Http\Request), Object(Closure))
#40 C:\xampp\htdocs\app\Http\Middleware\ApplyCspRules.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#41 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): BookStack\Http\Middleware\ApplyCspRules->handle(Object(BookStack\Http\Request), Object(Closure))
#42 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#43 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(697): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(672): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(BookStack\Http\Request))
#45 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(636): Illuminate\Routing\Router->runRoute(Object(BookStack\Http\Request), Object(Illuminate\Routing\Route))
#46 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Routing\Router.php(625): Illuminate\Routing\Router->dispatchToRoute(Object(BookStack\Http\Request))
#47 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router->dispatch(Object(BookStack\Http\Request))
#48 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(BookStack\Http\Request))
#49 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Http\Middleware\TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#50 C:\xampp\htdocs\app\Http\Middleware\TrustProxies.php(41): Illuminate\Http\Middleware\TrustProxies->handle(Object(BookStack\Http\Request), Object(Closure))
#51 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): BookStack\Http\Middleware\TrustProxies->handle(Object(BookStack\Http\Request), Object(Closure))
#52 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#53 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(BookStack\Http\Request), Object(Closure))
#54 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(BookStack\Http\Request), Object(Closure))
#55 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#56 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(BookStack\Http\Request), Object(Closure))
#57 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#58 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(BookStack\Http\Request), Object(Closure))
#59 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(BookStack\Http\Request))
#60 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 C:\xampp\htdocs\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(BookStack\Http\Request))
#62 C:\xampp\htdocs\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(BookStack\Http\Request))
#63 {main}
```

</details>

### Exact BookStack Version

v21.12.2

### PHP Version

7.3.12

### Hosting Environment

Windows Server 2019

**Comment by ssddanbrown** [comment]
Hi @Statium,
Can you try updating and report the error when using the latest version of BookStack?
The temporary location generation was tweaked slightly in the PDF generation library, for more recent versions.

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this.

**Comment by treverehrfurth** [comment]
I have a new instance of bookstack as of a couple days ago and I still get this error
