### ISSUE TITLE
Error 500 on a second instance

### ISSUE THREAD

**Issue by pBra1n** [BookStackApp/BookStack#3568]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I am having an issue with a second instance of Bookstack.  One instance works just fine (still running version 0.31.5).  We set up a second instance with the latest build and it is giving us a 500 error.  I have checked all the permissions on the folder, but can't figure out why it's not loading.

Below is what is in the error.log file:

<details>

```
PHP Fatal error:  Uncaught Error: Call to undefined method Illuminate\\Support\\Collection::getArrayableItems() in /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:31\nStack trace:\n#0 /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(15): Illuminate\\Support\\Collection->__construct(Array)\n#1 /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(16): collect(Array)\n#2 /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(598): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()\n#3 /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(579): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()\n#4 /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKerne in /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Collections/Collection.php on line 31
```

</details>

### Exact BookStack Version

22.06.2

### Log Content

```
#0 /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Collections/helpers.php(15): Illuminate\\Support\\Collection->__construct(Array)
#1 /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(16): collect(Array)
#2 /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(598): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()
#3 /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(579): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()
#4 /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(490): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKerne at /var/www/bookstack-it/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:31)
[stacktrace]
```

### PHP Version

7.4

### Hosting Environment

Ubuntu 18

**Comment by ssddanbrown** [comment]
Hi @pBra1n,

- What was your method of install for the second instance? (Are you following a specific guide)
- What is the result when running the `composer install --no-dev` update step within the install directory?

**Comment by ssddanbrown** [comment]
Since there's been no follow-up I'm going to close this. If the issue remains and is something you still require to be fixed respond to my previous comment and this can then be re-opened.
