### ISSUE TITLE
After updating to PHP 8.1, Uncaught ErrorExceptions occur in apache error log

### ISSUE THREAD

**Issue by morfie78** [BookStackApp/BookStack#3613]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

We updated from PHP 7.4 to PHP 8.1.  After restarting apache, Bookstack becomes inaccessible, and the apache error log is filled with:
```
[Tue Aug 02 07:54:43.444654 2022] [php:error] [pid 2562185] [client 51.158.66.83:41334] PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\\Support\\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1277\nStack trace:\n#0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Support/Collection.php(11): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/BookStack/vendor/composer/ClassLoader.php(444): include('...')\n#2 /var/www/BookStack/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile()\n#3 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Support/helpers.php(109): Composer\\Autoload\\ClassLoader->loadClass()\n#4 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(89): collect()\n#5 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\\Foundation\\PackageManifest->config()\n#6 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\\Foundation\\PackageManifest->aliases()\n#7 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219): Illuminate\\Foundation\\Bootstrap\\RegisterFacades->bootstrap()\n#8 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(156): Illuminate\\Foundation\\Application->bootstrapWith()\n#9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Foundation\\Http\\Kernel->bootstrap()\n#10 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()\n#11 /var/www/BookStack/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle()\n#12 {main} in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Support/Collection.php on line 11
[Tue Aug 02 07:54:43.444777 2022] [php:error] [pid 2562185] [client 51.158.66.83:41334] PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php:871\nStack trace:\n#0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(871): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies()\n#2 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()\n#3 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()\n#4 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(265): Illuminate\\Foundation\\Application->resolve()\n#5 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}()\n#6 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()\n#7 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()\n#8 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve()\n#9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make()\n#10 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(170): Illuminate\\Foundation\\Application->make()\n#11 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->getExceptionHandler()\n#12 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(100): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#13 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(134): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#14 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#15 {main}\n  thrown in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 871
```

### Exact BookStack Version

v22.07.1

### Log Content

[Tue Aug 02 07:54:43.444654 2022] [php:error] [pid 2562185] [client 51.158.66.83:41334] PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\\Support\\Collection::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Support/Collection.php:1277\nStack trace:\n#0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Support/Collection.php(11): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/BookStack/vendor/composer/ClassLoader.php(444): include('...')\n#2 /var/www/BookStack/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile()\n#3 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Support/helpers.php(109): Composer\\Autoload\\ClassLoader->loadClass()\n#4 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(89): collect()\n#5 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/PackageManifest.php(78): Illuminate\\Foundation\\PackageManifest->config()\n#6 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterFacades.php(26): Illuminate\\Foundation\\PackageManifest->aliases()\n#7 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(219): Illuminate\\Foundation\\Bootstrap\\RegisterFacades->bootstrap()\n#8 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(156): Illuminate\\Foundation\\Application->bootstrapWith()\n#9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Foundation\\Http\\Kernel->bootstrap()\n#10 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()\n#11 /var/www/BookStack/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle()\n#12 {main} in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Support/Collection.php on line 11
[Tue Aug 02 07:54:43.444777 2022] [php:error] [pid 2562185] [client 51.158.66.83:41334] PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php:871\nStack trace:\n#0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(871): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies()\n#2 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()\n#3 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()\n#4 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(265): Illuminate\\Foundation\\Application->resolve()\n#5 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Container\\Container->Illuminate\\Container\\{closure}()\n#6 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build()\n#7 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(785): Illuminate\\Container\\Container->resolve()\n#8 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Foundation\\Application->resolve()\n#9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(770): Illuminate\\Container\\Container->make()\n#10 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(170): Illuminate\\Foundation\\Application->make()\n#11 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->getExceptionHandler()\n#12 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(100): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#13 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(134): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#14 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#15 {main}\n  thrown in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 871

### PHP Version

8.1

### Hosting Environment

Ubuntu 20.04 dedicated linux machine, installed via install script.

**Comment by morfie78** [comment]
Fixed by re-running Bookstack upgrade process
