### ISSUE TITLE
Blank screen upon first loading Bookstack

### ISSUE THREAD

**Issue by lawyernobaka** [BookStackApp/BookStack#3772]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I cannot log in to Bookstack for the first time. When I navigate to the correct IP/port, all I get is a blank screen in Firefox. Trying other browsers, I get a 500 network error. Disabling VPN does not change results. All other docker images seem to be working as intended. I didn't see any issues that were the same as mine when I searched GitHub. I also manually updated the permissions for the uploads folder, but was unable to find the storage and cache folders to check theirs.

I provided the nginx log below. I can also provide the contents of laravel.log if necessary, but it's currently over 10K lines long.

Thanks for your help with this. I'll admit, I'm pretty new to all of this, so I really appreciate the guidance.

### Exact BookStack Version

v22.09.1

### Log Content

```
2022/10/08 02:15:46 [error] 322#322: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstackapp.users' doesn't exist in /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368
Stack trace:
#0 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): PDO->prepare()
#1 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\Database\Connection->select()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402): Illuminate\Database\Query\Builder->runSelect()
#6 /app/www/vend...PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstackapp.users' doesn't exist in /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368
Stack trace:
#0 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): PDO->prepare()
#1 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\Database\Connection->select()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402): Illuminate\Databas
2022/10/08 16:25:56 [error] 324#324: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstackapp.users' doesn't exist in /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368
Stack trace:
#0 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): PDO->prepare()
#1 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\Database\Connection->select()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402): Illuminate\Database\Query\Builder->runSelect()
#6 /app/www/vend...PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstackapp.users' doesn't exist in /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368
Stack trace:
#0 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): PDO->prepare()
#1 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\Database\Connection->select()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402): Illuminate\Databas
2022/10/08 16:26:50 [error] 324#324: *4 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstackapp.users' doesn't exist in /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368
Stack trace:
#0 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): PDO->prepare()
#1 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\Database\Connection->select()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402): Illuminate\Database\Query\Builder->runSelect()
#6 /app/www/vend...PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstackapp.users' doesn't exist in /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368
Stack trace:
#0 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): PDO->prepare()
#1 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#3 /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#4 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\Database\Connection->select()
#5 /app/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402): Illuminate\Database
```

### PHP Version

Unsure

### Hosting Environment

Portainer Docker Manager (v2.15.1) and Docker (v20.10.3-1308) via Synology NAS (DSM v7.1-42661 Update 4). No proxies, connected through Mullvad VPN.

**Comment by ssddanbrown** [comment]
Hi @lawyernobaka,
The error is showing that an expected database table does not exist. The fact it's the `users` table means that there's likely no database tables found.
Based on your log output, I'm assuming you're using the linuxserver.io container image? 
If so, this runs database migrations on startup.
Could you get the docker container output logs from a fresh restart of the container?
This container image logs out the migration details, and I'm expected we'd see relevant error detail there.

**Comment by lawyernobaka** [comment]
Have to do some errands, and then I'll report back. Thanks for looking into this.

**Comment by lawyernobaka** [comment]
Hello @ssddanbrown,

Yes, I'm using the linuxserver.io container image.

Copy/pasting the log I think you're referring to below, but let me know if you need something else.

<details>

```
cont-init: info: running /etc/cont-init.d/01-migrations
grep: /config/nginx/site-confs/default.conf: No such file or directory
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1026
User gid:    100
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/11-folders
cont-init: info: /etc/cont-init.d/11-folders exited 0
cont-init: info: running /etc/cont-init.d/12-samples
cont-init: info: /etc/cont-init.d/12-samples exited 0
cont-init: info: running /etc/cont-init.d/13-nginx
Setting resolver to  127.0.0.11
Setting worker_processes to 4
cont-init: info: /etc/cont-init.d/13-nginx exited 0
cont-init: info: running /etc/cont-init.d/14-php
cont-init: info: /etc/cont-init.d/14-php exited 0
cont-init: info: running /etc/cont-init.d/15-keygen
generating self-signed keys in /config/keys, you can replace these with your own keys if required
Generating a RSA private key
..............................+++++
.......................................+++++
writing new private key to '/config/keys/cert.key'
-----
cont-init: info: /etc/cont-init.d/15-keygen exited 0
cont-init: info: running /etc/cont-init.d/20-permissions
cont-init: info: /etc/cont-init.d/20-permissions exited 0
cont-init: info: running /etc/cont-init.d/50-config
New container detected. Setting up app folder and fixing permissions.
Generating BookStack app key for first run
App Key set to base64:[redacted] you can modify the file to update /config/BOOKSTACK_APP_KEY.txt
Running config - db_user set
**** APP_URL in /config/www/.env is being updated from https://example.com to http://192.168.1.159:6875 ****
**** If this is an existing install, you should run the following line from your host terminal to update the database URL entries: ****
************************************************************************
docker exec -it bookstack php /app/www/artisan bookstack:update-url https://example.com http://192.168.1.159:6875
************************************************************************

   Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = bookstackapp and table_name = migrations and table_type = 'BASE TABLE')

  at /app/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

      +36 vendor frames 
  37  /app/www/artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
cont-init: info: /etc/cont-init.d/50-config exited 0
cont-init: info: running /etc/cont-init.d/85-version-checks
cont-init: info: /etc/cont-init.d/85-version-checks exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun memcached (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
```

</details>

**Comment by ssddanbrown** [comment]
@lawyernobaka Yeah, that contains an error when the container attempts to migrate the database. Does not seem able to connect.

Is the database definitely running? And do the database details, configured for the BookStack container, definitely point to an active instance with valid user/password/database details?

**Comment by lawyernobaka** [comment]
I'm not entirely sure how to check, but here are the logs for the database. Parsing what I can, it seems like there's some additional configuration I may need to do?

ETA: As far as I can tell, the database is indeed running and, to some extent, configured for the Bookstack container, but I'm not to what extent and if it has a valid user/password/database details.

<details>


```
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1026
User gid:    100
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/30-config
cont-init: info: /etc/cont-init.d/30-config exited 0
cont-init: info: running /etc/cont-init.d/40-initialise-db
Setting Up Initial Databases
Installing MariaDB/MySQL system tables in '/config/databases' ...
2022-10-08 18:32:39 1 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1017: Can't find file: './mysql/' (errno: 2 "No such file or directory")
OK

To start mysqld at boot time you have to copy
support-files/mysql.server to the right place for your system


PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following command:

'/usr/bin/mysql_secure_installation'

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the MariaDB Knowledgebase at https://mariadb.com/kb

You can start the MariaDB daemon with:
cd '/usr' ; /usr/bin/mysqld_safe --datadir='/config/databases'

You can test the MariaDB daemon with mysql-test-run.pl
cd '/usr/mysql-test' ; perl mysql-test-run.pl

Please report any problems at https://mariadb.org/jira

The latest information about MariaDB is available at https://mariadb.org/.

Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

2022-10-08 18:34:02 0 [Note] mysqld (mysqld 10.5.17-MariaDB-log) starting as process 143 ...
2022-10-08 18:34:02 0 [Note] InnoDB: Uses event mutexes
2022-10-08 18:34:02 0 [Note] InnoDB: Compressed tables use zlib 1.2.12
2022-10-08 18:34:02 0 [Note] InnoDB: Number of pools: 1
2022-10-08 18:34:02 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2022-10-08 18:34:02 0 [Note] InnoDB: Using Linux native AIO
2022-10-08 18:34:02 0 [Note] InnoDB: Initializing buffer pool, total size = 268435456, chunk size = 134217728
2022-10-08 18:34:02 0 [Note] InnoDB: Completed initialization of buffer pool
2022-10-08 18:34:03 0 [Note] InnoDB: 128 rollback segments are active.
2022-10-08 18:34:03 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2022-10-08 18:34:03 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2022-10-08 18:34:03 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2022-10-08 18:34:03 0 [Note] InnoDB: 10.5.17 started; log sequence number 45118; transaction id 20
2022-10-08 18:34:03 0 [Note] Plugin 'FEEDBACK' is disabled.
2022-10-08 18:34:03 0 [Note] InnoDB: Loading buffer pool(s) from /config/databases/ib_buffer_pool
2022-10-08 18:34:03 0 [Note] InnoDB: Buffer pool(s) load completed at 221008 18:34:03
2022-10-08 18:34:05 0 [Note] Server socket created on IP: '::'.
2022-10-08 18:34:05 0 [Note] Reading of all Master_info entries succeeded
2022-10-08 18:34:05 0 [Note] Added new Master_info '' to hash table
2022-10-08 18:34:08 0 [Note] mysqld: ready for connections.
Version: '10.5.17-MariaDB-log'  socket: '/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
2022-10-08 18:34:09 0 [Note] mysqld (initiated by: root[root] @ localhost []): Normal shutdown
2022-10-08 18:34:09 0 [Note] Event Scheduler: Purging the queue. 0 events
2022-10-08 18:34:09 0 [Note] InnoDB: FTS optimize thread exiting.
2022-10-08 18:34:14 0 [Note] InnoDB: Starting shutdown...
2022-10-08 18:34:14 0 [Note] InnoDB: Dumping buffer pool(s) to /config/databases/ib_buffer_pool
2022-10-08 18:34:14 0 [Note] InnoDB: Buffer pool(s) dump completed at 221008 18:34:14
2022-10-08 18:34:15 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2022-10-08 18:34:15 0 [Note] InnoDB: Shutdown completed; log sequence number 45130; transaction id 23
2022-10-08 18:34:17 0 [Note] mysqld: Shutdown complete

Database Setup Completed
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/40-initialise-db exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
[ls.io-init] done.
221008 18:34:17 mysqld_safe Logging to '/config/databases/fc65646c3d9e.err'.
221008 18:34:18 mysqld_safe Starting mariadbd daemon with databases from /config/databases
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun mariadb (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
s6-rc: info: service 99-ci-service-check successfully started
```

</details>

**Comment by ssddanbrown** [comment]
@lawyernobaka Ultimately it's going to come down to the networking between these containers and the configuration set.
Are the configuration options aligned between the bookstack and database containers. Specifically the:

- database name
- database user
- database password

All three of these must be aligned. Additionally, the `DB_HOST` value for the BookStack container must be accessible and resolve to the database container, over port 3306. 
With these database, it may be the case, for both containers in play, that their configuration may only take affect on initial container start-up where persistent storage is active.

**Comment by lawyernobaka** [comment]
So looking at my docker compose, it seems like the database name, database user, and database passwords between Bookstack and its database are all in alignment. I'm not sure how to check that port 3306 is accessible and being used.

For reference, here's my docker compose script.

```
version: "2"
services:
  bookstack:
    image: ghcr.io/linuxserver/bookstack
    container_name: Bookstack
    environment:
      - PUID=1026
      - PGID=100 
      - APP_URL=http://192.168.1.159:6875
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=yourdbpass
      - DB_DATABASE=bookstackapp
    volumes:
      - /volume1/docker/bookstack:/config
    ports:
      - 6875:80
    restart: always
    depends_on:
      - bookstack_db
  bookstack_db:
    image: ghcr.io/linuxserver/mariadb
    container_name: Bookstack-DB
    environment:
      - PUID=1026
      - PGID=100
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=yourdbpass
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=yourdbpass
    volumes:
      - /volume1/docker/bookstackdb:/config
    restart: always
```

**Comment by ssddanbrown** [comment]
First step is to see if the bookstack container can resolve the given database hostname.
Could you access the console for [the console](https://docs.portainer.io/user/docker/containers/console) for the BookStack container, then run `ping bookstack_db` and confirm the output?

**Comment by lawyernobaka** [comment]
I let the command run for a bit, and it successfully sent almost 200 packets of data to bookstack_db.

```
root@[redacted]:/#ping bookstack_db
PING bookstack_db (172.20.0.2): 56 data bytes
64 bytes from 170.20.0.2: seq=0 ttl=64 time=0.107 ms
64 bytes from 170.20.0.2: seq=1 ttl=64 time=0.135 ms
```

And so on like this, averaging 0.1-0.2 milliseconds each time.

ETA: wording.

**Comment by lawyernobaka** [comment]
@ssddanbrown Would you be able to help further? No worries if not - I just would like to know so I can decide how to proceed from here.

**Comment by ssddanbrown** [comment]
@lawyernobaka The next step I'd take would be to:

- Access the bookstack container via bash.
- Install MySQL client (If not already installed).
- Attempted to start a mysql connection from the command line to the database system.

**Comment by lawyernobaka** [comment]
@ssddanbrown Ah, I feel a bit silly now, but installing MariaDB seems to have fixed this particular issue. I could have sworn I was using other dockers that relied on MariaDB (and, thus, would have figured it was installed), but apparently not.

Thanks for your advice and guiding me through troubleshooting this. Hope you have a lovely day!
