### ISSUE TITLE
HTTP 500 returned after upgrade to 2022.11

### ISSUE THREAD

**Issue by RZR7332** [BookStackApp/BookStack#3893]
### Describe the Bug

After upgrading to 2022.11 earlier this morning, I can no longer access BookStack. Apache prints logs similar to the below:

Dec 02 11:16:31 Bookstack apache2[6771]: [proxy_fcgi:error] [pid 6771:tid 139780858365504] [client x.x.x.x] AH01071: Got error 'PHP message: PHP Warning:  require(/var/www/bookstack/vendor/composer/../symfony/polyfill-php80/bootstrap.php): Failed to open stream: Permission denied in /var/www/bookstack/vendor/composer/autoload_real.php on line 55PHP message: PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/bookstack/vendor/composer/../symfony/polyfill-php80/bootstrap.php' (include_path='.:/usr/share/php') in /var/www/bookstack/vendor/composer/autoload_real.php:55\nStack trace:\n#0 /var/www/bookstack/vendor/composer/autoload_real.php(38): composerRequire78dc58be6a5a48aa3ce6f7d6710337ec()\n#1 /var/www/bookstack/vendor/autoload.php(12): ComposerAutoloaderInit78dc58be6a5a48aa3ce6f7d6710337ec::getLoader()\n#2 /var/www/bookstack/public/index.php(34): require('...')\n#3 {main}\n  thrown in /var/www/bookstack/vendor/composer/autoload_real.php on line 55'

While the services for Apache and PHP start successfully, I cannot access the web page as Apache returns a 500 page and prints the above. Line 55 in /var/www/bookstack/vendor/composer/autoload_real.php is as below:

require $file;

File is owned by www-data which I presume is expected.

### Steps to Reproduce

Upgrade to 2022.11 from 2022.10. Installation working as expected prior to upgrade.

### Expected Behaviour

Apache should present the login page as expected after the upgrade.

### Browser Details

Edge 107.0.1418.62  on Windows 11

### Exact BookStack Version

2022.11

### PHP Version

8.1

### Hosting Environment

Ubuntu 22.04 LTS LXC, installed using official script.

**Comment by RZR7332** [comment]
Apologies, I think this should actually have the Support label, not Bug. I cannot change it myself it seems.
