### ISSUE TITLE
Issue updating from v23.01.1 to 23.02

### ISSUE THREAD

**Issue by infotts-py** [BookStackApp/BookStack#4120]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I updated Ubuntu to 22.04.2 LTS (GNU/Linux 5.15.0-67-generic x86_64).

When I update bookstack, I get this error message 

<details>

```
PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\String\normalizer_is_normalized() in /usr/share/php/Symfony/Component/String/UnicodeString.php:37
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Helper/Helper.php(65): Symfony\Component\String\UnicodeString->__construct()
#1 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(383): Symfony\Component\Console\Helper\Helper::width()
#2 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(322): Symfony\Component\Console\Helper\ProgressBar->setMaxSteps()
#3 /usr/share/php/Composer/Util/Loop.php(89): Symfony\Component\Console\Helper\ProgressBar->start()
#4 /usr/share/php/Composer/Installer/InstallationManager.php(497): Composer\Util\Loop->wait()
#5 /usr/share/php/Composer/Installer/InstallationManager.php(362): Composer\Installer\InstallationManager->waitOnPromises()
#6 /usr/share/php/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#7 /usr/share/php/Composer/Installer.php(754): Composer\Installer\InstallationManager->execute()
#8 /usr/share/php/Composer/Installer.php(281): Composer\Installer->doInstall()
#9 /usr/share/php/Composer/Command/InstallCommand.php(139): Composer\Installer->run()
#10 /usr/share/php/Symfony/Component/Console/Command/Command.php(298): Composer\Command\InstallCommand->execute()
#11 /usr/share/php/Symfony/Component/Console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#12 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#13 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#14 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun()
#15 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#16 /usr/bin/composer(84): Composer\Console\Application->run()
#17 {main}
  thrown in /usr/share/php/Symfony/Component/String/UnicodeString.php on line 37

Fatal error: Uncaught Error: Call to undefined function Symfony\Component\String\normalizer_is_normalized() in /usr/share/php/Symfony/Component/String/UnicodeString.php:37
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Helper/Helper.php(65): Symfony\Component\String\UnicodeString->__construct()
#1 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(383): Symfony\Component\Console\Helper\Helper::width()
#2 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(322): Symfony\Component\Console\Helper\ProgressBar->setMaxSteps()
#3 /usr/share/php/Composer/Util/Loop.php(89): Symfony\Component\Console\Helper\ProgressBar->start()
#4 /usr/share/php/Composer/Installer/InstallationManager.php(497): Composer\Util\Loop->wait()
#5 /usr/share/php/Composer/Installer/InstallationManager.php(362): Composer\Installer\InstallationManager->waitOnPromises()
#6 /usr/share/php/Composer/Installer/InstallationManager.php(282): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#7 /usr/share/php/Composer/Installer.php(754): Composer\Installer\InstallationManager->execute()
#8 /usr/share/php/Composer/Installer.php(281): Composer\Installer->doInstall()
#9 /usr/share/php/Composer/Command/InstallCommand.php(139): Composer\Installer->run()
#10 /usr/share/php/Symfony/Component/Console/Command/Command.php(298): Composer\Command\InstallCommand->execute()
#11 /usr/share/php/Symfony/Component/Console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#12 /usr/share/php/Symfony/Component/Console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#13 /usr/share/php/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#14 /usr/share/php/Symfony/Component/Console/Application.php(171): Composer\Console\Application->doRun()
#15 /usr/share/php/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#16 /usr/bin/composer(84): Composer\Console\Application->run()
#17 {main}
  thrown in /usr/share/php/Symfony/Component/String/UnicodeString.php on line 37
```

</details>

I came back to a previous checkpoint. I tried upgrading PHP (8.0.28) and composer (2.5.4) to the latest versions. When I update bookstack I still get the same error message.

Any idea what I should do ?

### Exact BookStack Version

23.02

### PHP Version

8.0.28

### Hosting Environment

VM in Hyper-V running Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-67-generic x86_64)

**Comment by ssddanbrown** [comment]
Hi @infotts-py,

My guess that things have got a bit messy in the upgrade. I can you you're using the system-provided composer package based on your log. It may be that the system-provided version and composer and the PHP version in use (Which is behind for a Ubuntu 22.04.2 instance) are incompatible. 

I'd suggest removing the system-provided version of composer and instead download a copy of composer directly. There's some high-level guidance for this [on our update page](https://www.bookstackapp.com/docs/admin/updates/#updating-composer).

You'd also want to probably get on a later PHP version as I don't think you'd be getting updates/support for PHP 8.0 on Ubuntu 22.04.

**Comment by infotts-py** [comment]
Hi Dan,

Sorry my mistake I did have PHP at 8.2. 
php --version
PHP 8.2.3 (cli) (built: Feb 14 2023 16:58:12) (NTS)

I followed your suggestion and uninstalled composer instead of simply updating. I then reinstalled it as the guide indicates. I was then able to upgrade bookstack successfully to v23.02.1!

Thank you!

**Comment by ssddanbrown** [comment]
Good news! I'll therefore close this off.
