### ISSUE TITLE
Can't update to lts version

### ISSUE THREAD

**Issue by Ludo-code** [BookStackApp/BookStack#4129]
### Describe the Bug

If i run git pull origin release he say me : 

```
remote: Enumerating objects: 1671, done.
remote: Counting objects: 100% (1100/1100), done.
remote: Total 1671 (delta 1100), reused 1100 (delta 1100), pack-reused 571
Receiving objects: 100% (1671/1671), 1.61 MiB | 24.22 MiB/s, done.
Resolving deltas: 100% (1389/1389), completed with 492 local objects.
From https://github.com/BookStackApp/BookStack
 * branch              release    -> FETCH_HEAD
   e794c977..2dad92d1  release    -> origin/release
Updating e794c977..2dad92d1
error: Your local changes to the following files would be overwritten by merge:
        resources/lang/ar/settings.php
        resources/lang/ca/settings.php
        resources/lang/en/settings.php
        resources/lang/he/settings.php
        resources/lang/it/activities.php
        resources/lang/it/auth.php
        resources/lang/it/common.php
        resources/lang/it/components.php
        resources/lang/it/entities.php
        resources/lang/it/errors.php
        resources/lang/it/pagination.php
        resources/lang/it/passwords.php
        resources/lang/it/settings.php
        resources/lang/it/validation.php
        resources/lang/ko/settings.php
        resources/lang/ru/settings.php
        resources/lang/tr/settings.php
        resources/lang/zh_CN/settings.php
Please commit your changes or stash them before you merge.
Aborting
```

and doesn't update something...

### Steps to Reproduce

try a git pull origin release in the BookStack v22.11.1 version...

### Expected Behaviour

Update can be made...

### Exact BookStack Version

v22.11.1

### PHP Version

8.1

### Hosting Environment

Ubuntu server 22.04.2

**Comment by ssddanbrown** [comment]
Git is detecting that there's unexpected changes to those listed language files so is stopping to prevent loosing changes. Have you made intentional changes to any language files?

**Comment by Ludo-code** [comment]
> Git is detecting that there's unexpected changes to those listed language files so is stopping to prevent loosing changes. Have you made intentional changes to any language files? 

No I don't have changed anything on the file mentioned...

**Comment by ssddanbrown** [comment]
@Ludo-code Okay. Just so we can be sure can you go to your BookStack install directory, then run `git diff resources/lang/it/activities.php` then share the output?

**Comment by Ludo-code** [comment]
Here is the output :

```
git diff resources/lang/it/activities.php
diff --git a/resources/lang/it/activities.php b/resources/lang/it/activities.php
old mode 100755
new mode 100644
```

**Comment by ssddanbrown** [comment]
@Ludo-code Thanks. Looks like permission changes for a select few files. From the BookStack directory, can you run `git config core.fileMode false` then run `git status`. If that last command does not list any files, you can attempt updating again.

**Comment by Ludo-code** [comment]
After updating bookstack say an unknown error as occurred, I can't connect send test email or see any page...

Doesn't write any log in /var/log/apache2

<details><summary>Details</summary>
<p>

![Screenshot_20230325_131922_edit_53475346555224.jpg](https://user-images.githubusercontent.com/56892223/227716988-1c78e051-9465-4601-af39-2437ed170ffd.jpg)

</p>
</details>

**Comment by ssddanbrown** [comment]
@Ludo-code Did the update commands run without error?

Otherwise, please look to the BookStack error log for detail: https://www.bookstackapp.com/docs/admin/debugging/#error-log-file

**Comment by Ludo-code** [comment]
No error during update...

But found this error :

[2023-03-25 12:12:25] production.ERROR: SQLSTATE[42S22>
[stacktrace]

**Comment by ssddanbrown** [comment]
@Ludo-code Is that the full error message? I'd expect a bit more.

Could you also re-run the `php artisan migrate` update command and share the output.

**Comment by Ludo-code** [comment]
Here is an snippet of log file error because on mobile it's difficult to copy and past :

```

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'action' in 'where clause' at /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368)                                             [stacktrace]                                           #0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): PDO->prepare()    #1 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()      #2 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\\Database\\Connection->runQueryCallback()                     #3 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\\Database\\Connection->run()                                  #4 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2414): Illuminate\\Database\\Connection->select()                           #5 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2402): Illuminate\\Database\\Query\\Builder->runSelect()                    #6 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2936): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()                                              #7 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2403): Illuminate\\Database\\Query\\Builder->onceWithColumns()              #8 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2863): Illuminate\\Database\\Query\\Builder->get()                          #9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2791): Illuminate\\Database\\Query\\Builder->aggregate()                    #10 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1657): Illuminate\\Database\\Query\\Builder->count()                    #11 /var/www/BookStack/app/Auth/Permissions/PermissionApplicator.php(112): Illuminate\\Database\\Eloquent\\Builder->__call()                                         #12 /var/www/BookStack/app/helpers.php(81): BookStack\\Auth\\Permissions\\PermissionApplicator->checkUserHasEntityPermissionOnAny()                                  #13 /var/www/BookStack/storage/framework/views/01280bf8d0fad359485acdd2650fba67c8971867.php(35): userCanOnAny()                                                      #14 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...') #15 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()                                                      #16 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()                      #17 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()             #18 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get()                                  #19 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()                                             #20 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()                                           #21 /var/www/BookStack/storage/framework/views/c2af1b91134bbaf36167ca00a30e5400417272df.php(39): Illuminate\\View\\View->render()                                    #22 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...') #23 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()                                                      #24 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()                      #25 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()             #26 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get()                                  #27 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()                                             #28 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()                                           #29 /var/www/BookStack/storage/framework/views/a626fbe2b5a63439d8e640abb3660a32dcbc7bc0.php(16): Illuminate\\View\\View->render()                                    #30 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(107): require('...') #31 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(108): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()                                                      #32 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()                      #33 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(61): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()             #34 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(139): Illuminate\\View\\Engines\\CompilerEngine->get()                                  #35 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(122): Illuminate\\View\\View->getContents()                                             #36 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(91): Illuminate\\View\\View->renderContents()                                           #37 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()                                               #38 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/H
```


For php artisan migrate :


INFO  Nothing to migrate.

**Comment by ssddanbrown** [comment]
@Ludo-code That indicates the code is out of date, which would mean the first update step (the `git pull`) is not completing properly. Can you share the output of `git status`.

**Comment by Ludo-code** [comment]
Git status say :

```
git status
On branch release
Your branch is up to date with 'origin/release'.

nothing to commit, working tree clean
```

**Comment by ssddanbrown** [comment]
@Ludo-code Alright, what's the full output when you run the `git pull origin release` step?

**Comment by Ludo-code** [comment]
Here is it :

```
remote: Enumerating objects: 139, done.
remote: Counting objects: 100% (137/137), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 139 (delta 102), reused 118 (delta 99), pack-reused 2
Receiving objects: 100% (139/139), 192.66 KiB | 6.88 MiB/s, done.
Resolving deltas: 100% (102/102), completed with 77 local objects.
From https://github.com/BookStackApp/BookStack
 * branch              release    -> FETCH_HEAD
   2dad92d1..c9ed32e5  release    -> origin/release
Updating 2dad92d1..c9ed32e5
Fast-forward
 .../Controllers/RoleController.php  |   3 +-
 composer.json                       |   2 +-
 composer.lock                       | 274 +++++------
 lang/ar/settings.php                |   4 +-
 lang/bg/settings.php                |   4 +-
 lang/bs/settings.php                |   4 +-
 lang/ca/settings.php                |   4 +-
 lang/cs/activities.php              |   6 +-
 lang/cs/entities.php                |   2 +-
 lang/cs/settings.php                |  10 +-
 lang/cy/settings.php                |   4 +-
 lang/da/settings.php                |   4 +-
 lang/de/settings.php                |  24 +-
 lang/de_informal/activities.php     |   2 +-
 lang/de_informal/entities.php       |  10 +-
 lang/de_informal/errors.php         |   2 +-
 lang/de_informal/settings.php       |  24 +-
 lang/el/activities.php              |   6 +-
 lang/el/entities.php                |  50 +-
 lang/el/errors.php                  |   2 +-
 lang/el/settings.php                |  32 +-
 lang/en/settings.php                |   4 +-
 lang/es/settings.php                |   4 +-
 lang/es_AR/settings.php             |   4 +-
 lang/et/settings.php                |   4 +-
 lang/eu/settings.php                |   4 +-
 lang/fa/settings.php                |   4 +-
 lang/fr/activities.php              |   6 +-
 lang/fr/entities.php                |  12 +-
 lang/fr/settings.php                |   6 +-
 lang/he/activities.php              |   2 +-
 lang/he/settings.php                |   4 +-
 lang/hr/settings.php                |   4 +-
 lang/hu/settings.php                |   4 +-
 lang/id/settings.php                |   4 +-
 lang/it/settings.php                |   4 +-
 lang/ja/settings.php                |   4 +-
 lang/ka/settings.php                |   4 +-
 lang/ko/settings.php                |   4 +-
 lang/lt/settings.php                |   4 +-
 lang/lv/activities.php              |  26 +-
 lang/lv/auth.php                    |  10 +-
 lang/lv/common.php                  |  10 +-
 lang/lv/editor.php                  |  10 +-
 lang/lv/entities.php                |  94 ++--
 lang/lv/errors.php                  |   4 +-
 lang/lv/settings.php                |  18 +-
 lang/nb/settings.php                |   4 +-
 lang/nl/activities.php              |   6 +-
 lang/nl/entities.php                |  26 +-
 lang/nl/errors.php                  |   2 +-
 lang/nl/settings.php                |  22 +-
 lang/pl/settings.php                |   4 +-
 lang/pt/activities.php              |   6 +-
 lang/pt/entities.php                |   2 +-
 lang/pt/settings.php                |  10 +-
 lang/pt_BR/settings.php             |   4 +-
 lang/ro/settings.php                |   4 +-
 lang/ru/settings.php                |   4 +-
 lang/sk/settings.php                |   4 +-
 lang/sl/settings.php                |   4 +-
 lang/sv/settings.php                |   4 +-
 lang/tr/settings.php                |   4 +-
 lang/uk/settings.php                |   4 +-
 lang/uz/settings.php                |   4 +-
 lang/vi/settings.php                |   4 +-
 lang/zh_CN/settings.php             |   4 +-
 lang/zh_TW/settings.php             |   4 +-
 .../views/users/delete.blade.php    |  48 +-
 tests/Permissions/RolesTest.php     |  16 +
 tests/User/UserManagementTest.php   |   1 +
 version                             |   2 +-
 72 files changed, 470 insertions(+), 458 deletions(-)
```

**Comment by ssddanbrown** [comment]
Okay, looks like that had not been ran since permissions change. Well you should have updated files now if that was the full output. Run the remaining two update steps again:

```bash
composer install --no-dev
php artisan migrate
```

Then hopefully you'll be back to normal.

**Comment by Ludo-code** [comment]
Yes working fine thanks you so much :)

**Comment by ssddanbrown** [comment]
Awesome! Good to hear!
