### ISSUE TITLE
Base table or view not found: 1146 Table 'bookstack.users' doesn't exist in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414

### ISSUE THREAD

**Issue by stereochoc** [BookStackApp/BookStack#4168]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

Hello i just have a fresh install of bookstack. All the website is ok. I can login as admin. The database was created and the user table is exist but when i try to create a user i have this error :

<details><summary>Details</summary>
<p>

```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstack.users' doesn't exist in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414\nStack trace:\n#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): PDO->prepare()\n#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()\n#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()\n#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate\\Database\\Connection->run()\n#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2706): Illuminate\\Database\\Connection->select()\n#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\\Database\\Query\\Builder->runSelect()\n#6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()\n#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2695): Illuminate\\Database\\Query\\Builder->onceWithColumns()\n#8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(710): Illuminate\\Database\\Query\\Builder->get()\n#9 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(694): Illuminate\\Database\\Eloquent\\Builder->getModels()\n#10 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(296): Illuminate\\Database\\Eloquent\\Builder->get()\n#11 /var/www/bookstack/app/Auth/User.php(104): Illuminate\\Database\\Eloquent\\Builder->first()\n#12 /var/www/bookstack/app/helpers.php(38): BookStack\\Auth\\User::getDefault()\n#13 /var/www/bookstack/app/Settings/SettingService.php(62): user()\n#14 /var/www/bookstack/storage/framework/views/58966642253d57ffe4f154d44ae65835f6011243.php(4): BookStack\\Settings\\SettingService->getForCurrentUser()\n#15 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')\n#16 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()\n#17 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()\n#18 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()\n#19 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()\n#20 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()\n#21 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()\n#22 /var/www/bookstack/storage/framework/views/444e2e0a8c776f8bed9002e3000a037539df392e.php(16): Illuminate\\View\\View->render()\n#23 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(109): require('...')\n#24 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(110): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()\n#25 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()\n#26 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(70): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()\n#27 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()\n#28 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()\n#29 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()\n#30 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()\n#31 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()\n#32 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()\n#33 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()\n#34 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(629): Illuminate\\Routing\\ResponseFactory->view()\n#35 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#36 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#37 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#38 /var/www/bookstack/app/Exceptions/Handler.php(66): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#39 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(229): BookStack\\Exceptions\\Handler->render()\n#40 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(206): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#41 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#42 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#43 {main}\n\nNext Illuminate\\Database\\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bookstack.users' doesn't exist (SQL: select * from `users` where `system_name` = public limit 1) in /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php:760\nStack trace:\n#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()\n#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate\\Database\\Connection->run()\n#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2706): Illuminate\\Database\\Connection->select()\n#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\\Database\\Query\\Builder->runSelect()\n#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()\n#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2695): Illuminate\\Database\\Query\\Builder->onceWithColumns()\n#6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(710): Illuminate\\Database\\Query\\Builder->get()\n#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(694): Illuminate\\Database\\Eloquent\\Builder->getModels()\n#8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(296): Illuminate\\Database\\Eloquent\\Builder->get()\n#9 /var/www/bookstack/app/Auth/User.php(104): Illuminate\\Database\\Eloquent\\Builder->first()\n#10 /var/www/bookstack/app/helpers.php(38): BookStack\\Auth\\User::getDefault()\n#11 /var/www/bookstack
```

</p>
</details> 

### Exact BookStack Version

v23.02.3

### Hosting Environment

Ubuntu 20.04

**Comment by ssddanbrown** [comment]
Hi @stereochoc,
That's an odd issue to get, especially if you can login fine.

- How exactly did you install BookStack?
- What's the current output when you run `git status` in your BookStack install folder?
- What's the current output when you run `php artisan migrate` in your BookStack install folder?

**Comment by stereochoc** [comment]
hello thanks for your response. I use the script for ubuntu installation
![image](https://user-images.githubusercontent.com/105720082/231173514-7e7855db-ad80-4ce5-aca6-3c7d43e7f2b6.png)

When i run git status i have this 
![image](https://user-images.githubusercontent.com/105720082/231173689-895c44e5-177f-4ede-b399-4d5a99cb9734.png)

When i run php artisan migrate i have this 
![image](https://user-images.githubusercontent.com/105720082/231173843-b0c9c219-cb99-4940-b4cb-9f496a2f48cc.png)

**Comment by stereochoc** [comment]
more, i can create shelves, i can create books. But on a book when i want to add a page, i can write text content, text title, etc but when i want to save i have this error 
![image](https://user-images.githubusercontent.com/105720082/231227528-7b9aace4-d06c-4a94-9c72-195ea966b24f.png)

**Comment by ssddanbrown** [comment]
@stereochoc Thanks.

Can you try the `git status` command again, but this time via sudo (`sudo git status`).
Also, please re-run the `php artisan migrate` command but this time answer `yes` at the question shown in your screenshot.

**Comment by stereochoc** [comment]
i have completly reinstall the server from ubuntu 20 to 22 and reinstall bookstack and all is working great now. Indeed thanks for the support

**Comment by ssddanbrown** [comment]
@stereochoc Good to hear things are now working. Will therefore close this off.
