### ISSUE TITLE
Upgrade from v21.12 to v23.05 - Settings "Page Not Found"

### ISSUE THREAD

**Issue by dilonbuser** [BookStackApp/BookStack#4351]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

After upgrading from v21.12 to v23.05 I receive a "Page Not Found" error message when accessing the "Settings" page. I have ready through dozens of Github and internet articles. None I've found seem to address this issue. 
![image](https://github.com/BookStackApp/BookStack/assets/91499478/f63c3c2b-6633-403e-b7b4-e9b1642888e3)

![image](https://github.com/BookStackApp/BookStack/assets/91499478/a7c36de1-83ff-41de-b826-c7ca011d1cf2)

I have no issue accessing other pages 
![image](https://github.com/BookStackApp/BookStack/assets/91499478/29434f37-760b-4fdd-b415-77a5a6859e6b)

1. I've updated the composer (Composer version 2.5.8 2023-06-09 17:13:21)
2. I've completed the php and system update steps related to the "v23.02 and higher" post
![image](https://github.com/BookStackApp/BookStack/assets/91499478/65237be5-dad6-4f92-abd3-260ce9eb7626)
3.  I've verified that no other PHP version is enabled and running most current. (Module php8.2 already enabled)
4. All steps using the update instructions complete without error. 

### Exact BookStack Version

v21.12

### Log Content

<details><summary>Details</summary>
<p>

```
[2023-06-29 16:18:04] production.ERROR: Method BookStack\Http\Controllers\BookController::showPermissions does not exist. {"userId":3,"exception":"[object] (BadMethodCallException(code: 0): Method BookStack\\Http\\Controllers\\BookController::showPermissions does not exist. at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:68)
[stacktrace]
#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): Illuminate\\Routing\\Controller->__call()
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#6 /var/www/bookstack/app/Http/Middleware/Authenticate.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): BookStack\\Http\\Middleware\\Authenticate->handle()
#8 /var/www/bookstack/app/Http/Middleware/Localization.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): BookStack\\Http\\Middleware\\Localization->handle()
#10 /var/www/bookstack/app/Http/Middleware/RunThemeActions.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): BookStack\\Http\\Middleware\\RunThemeActions->handle()
#12 /var/www/bookstack/app/Http/Middleware/CheckEmailConfirmed.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): BookStack\\Http\\Middleware\\CheckEmailConfirmed->handle()
#14 /var/www/bookstack/app/Http/Middleware/PreventAuthenticatedResponseCaching.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): BookStack\\Http\\Middleware\\PreventAuthenticatedResponseCaching->handle()
#16 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#18 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#20 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#22 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#23 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#25 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#27 /var/www/bookstack/app/Http/Middleware/ApplyCspRules.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): BookStack\\Http\\Middleware\\ApplyCspRules->handle()
#29 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Pipeline\\Pipeline->then()
#31 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#32 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#33 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#34 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#35 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#36 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/bookstack/app/Http/Middleware/TrustProxies.php(41): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#38 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): BookStack\\Http\\Middleware\\TrustProxies->handle()
#39 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#41 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#42 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#44 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#46 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#48 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#49 /var/www/bookstack/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#50 {main}
"}
```

</p>
</details> 

### PHP Version

8.2.7

### Hosting Environment

Ubuntu 20.04 Virtual Machine. I'm unsure if it was build using the script or the github manual steps.

**Comment by dilonbuser** [comment]
I should add. I've tried this upgrade path multiple over the past several months moving from v21.12 to 22.03, 22.04, 22.05, 22.08, 22.10. Always have the same issue with the Settings Page not found.

**Comment by ssddanbrown** [comment]
Thanks for the details @dilonbuser.

- In regards to the log content shared, can you confirm if this message is logged when you cause the reported issue to appear? The error log messages are time-stamped. Just because that particular error does not really relate to code I'd expect to be used in the settings.
- Can you provide the output of `git status` from your install directory, after updating to the latest version?
- Can you confirm what webserver you're using and, if possible, provide the server config (redacted if needed). The 20.04 install script would use apache and create a config at `/etc/apache2/sites-available/bookstack.conf`.

**Comment by dilonbuser** [comment]
> Thanks for the details @dilonbuser.
> 
>

>  * In regards to the log content shared, can you confirm if this message is logged when you cause the reported issue to appear? The error log messages are time-stamped. Just because that particular error does not really relate to code I'd expect to be used in the settings. 

Doing a tail on the log file, does not appear to be changed when I click on the settings link. I didn't know where it would like that so I put the log info that I thought may be pertinent. 
> * Can you provide the output of `git status` from your install directory, after updating to the latest version?
  ```
cd /var/www/bookstack/
  git status
  fatal: detected dubious ownership in repository at '/var/www/bookstack'
  To add an exception for this directory, call:
          git config --global --add safe.directory /var/www/bookstack
```

> > * Can you confirm what webserver you're using and, if possible, provide the server config (redacted if needed). The 20.04 install script would use apache and create a config at `/etc/apache2/sites-available/bookstack.conf`.

We are using apache
```
cat /etc/apache2/sites-available/bookstack.conf
<VirtualHost *:80>
        Redirect / https://<SERVER REDACTED>/
</VirtualHost>
<VirtualHost *:443>
        ServerName <SERVER REDACTED>

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/bookstack/public/

        SSLEngine on
        SSLCertificateKeyFile /etc/apache2/ssl/server.key
        SSLCertificateFile /etc/apache2/ssl/wildcard.pem
        SSLProtocol -all +TLSv1.2
        Protocols h2 http/1.1
    <Directory /var/www/bookstack/public/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
        <IfModule mod_rewrite.c>
            <IfModule mod_negotiation.c>
                Options -MultiViews -Indexes
            </IfModule>

            RewriteEngine On

            # Handle Authorization Header
            RewriteCond %{HTTP:Authorization} .
            RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

            # Redirect Trailing Slashes If Not A Folder...
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_URI} (.+)/$
            RewriteRule ^ %1 [L,R=301]

            # Handle Front Controller...
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^ index.php [L]
        </IfModule>
    </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```

**Comment by dilonbuser** [comment]
@ssddanbrown not sure if you saw my response to your questions. What other information can I provide to help diagnose this issue? Thanks for your help on this.

**Comment by ssddanbrown** [comment]
Sorry @dilonbuser,

- Can you run the suggested command in the previous output (`git config --global --add safe.directory /var/www/bookstack`) then run `git status` again and provide the output?
- Can you share the output of running `ls -alh /var/www/bookstack/bootstrap/cache`?
- Cat you share the output for runnning `cat /var/www/bookstack/version`?

**Comment by dilonbuser** [comment]
No worries @ssddanbrown  - I appreciate your assistance. 

> Sorry @dilonbuser,
> 
> * Can you run the suggested command in the previous output (`git config --global --add safe.directory /var/www/bookstack`) then run `git status` again and provide the output?

The .env.bak file is just a backup of the original .env file. I've also change the favicon from stock. 
![image](https://github.com/BookStackApp/BookStack/assets/91499478/a9079dbf-9740-4af4-a7e8-5ad53db9263e)
```
admin@bookstack:/var/www/bookstack$ git config --global --add safe.directory /var/www/bookstack
admin@bookstack:/var/www/bookstack$ git status
On branch release
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   public/icon.ico
        modified:   storage/clockwork/.gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .env.bak
        public/favicon.ico.bak

no changes added to commit (use "git add" and/or "git commit -a")
admin@bookstack:/var/www/bookstack$

```


> * Can you share the output of running `ls -alh /var/www/bookstack/bootstrap/cache`?
![image](https://github.com/BookStackApp/BookStack/assets/91499478/66a1295a-d306-4597-ba55-0746de7a4056)


> * Cat you share the output for runnning `cat /var/www/bookstack/version`?
![image](https://github.com/BookStackApp/BookStack/assets/91499478/835e3a40-010e-46b6-9b17-b56ee0a0225b)

**Comment by ssddanbrown** [comment]
Thanks @dilonbuser, Looks like someone ran an optimization/cache command back in March of 2022.
Please delete the `/var/www/bookstack/bootstrap/cache/routes-v7.php` file.

**Comment by dilonbuser** [comment]
> Thanks @dilonbuser, Looks like someone ran an optimization/cache command back in March of 2022. Please delete the `/var/www/bookstack/bootstrap/cache/routes-v7.php` file.

That did it! I think that routes file was created accidentally when we were first working through the upgrade process. 

Thank so much @ssddanbrown for your help. We are very excited to check out changes and improvements you've made since the v21.12 release!

Please close this issue.

**Comment by ssddanbrown** [comment]
Good to hear it's sorted! Will therefore close.
