### ISSUE TITLE
Mailing fails after update to 23.06.1

### ISSUE THREAD

**Issue by pythoninja** [BookStackApp/BookStack#4365]
### Describe the Bug

Looks like, something wrong with mail dependencies after updating to 23.06.1.

### Steps to Reproduce

Updating process from 23.06:
1. git pull origin release
2. composer install --no-dev
3. php artisan migrate
4. php artisan cache:clear && php artisan config:clear && php artisan view:clear

Steps:
1. go to https://bookstack/settings/maintenance and press "Send test email" - says ok
2. go to https://bookstack/password/email and try to recover password - says ok

I am using bookstack-queue service as described on https://www.bookstackapp.com/docs/admin/email-webhooks/#queue-worker-process

The email is not working properly. Here is errors from log I found:
<details><summary>laravel.log</summary>

```
[2023-07-06 04:32:48] production.ERROR: include(/var/www/bookstack/vendor/composer/../symfony/mailer/Transport/Smtp/EsmtpTransportFactory.php): Failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): include(/var/www/bookstack/vendor/composer/../symfony/mailer/Transport/Smtp/EsmtpTransportFactory.php): Failed to open stream: No such file or directory at /var/www/bookstack/vendor/composer/ClassLoader.php:576)
[stacktrace]
#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/bookstack/vendor/composer/ClassLoader.php(576): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/bookstack/vendor/composer/ClassLoader.php(576): include('...')
#3 /var/www/bookstack/vendor/composer/ClassLoader.php(427): Composer\\Autoload\\{closure}()
#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(175): Composer\\Autoload\\ClassLoader->loadClass()
#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(164): Illuminate\\Mail\\MailManager->createSmtpTransport()
#6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(122): Illuminate\\Mail\\MailManager->createSymfonyTransport()
#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(97): Illuminate\\Mail\\MailManager->resolve()
#8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Mail/MailManager.php(75): Illuminate\\Mail\\MailManager->get()
#9 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(64): Illuminate\\Mail\\MailManager->mailer()
#10 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(148): Illuminate\\Notifications\\Channels\\MailChannel->send()
#11 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(106): Illuminate\\Notifications\\NotificationSender->sendToNotifiable()
#12 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\\Notifications\\NotificationSender->Illuminate\\Notifications\\{closure}()
#13 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(101): Illuminate\\Notifications\\NotificationSender->withLocale()
#14 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(54): Illuminate\\Notifications\\NotificationSender->sendNow()
#15 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Notifications/SendQueuedNotifications.php(112): Illuminate\\Notifications\\ChannelManager->sendNow()
#16 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Notifications\\SendQueuedNotifications->handle()
#17 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#19 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#20 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#21 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#22 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#23 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#25 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\\Bus\\Dispatcher->dispatchNow()
#26 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#27 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#29 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#30 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#31 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(425): Illuminate\\Queue\\Jobs\\Job->fire()
#32 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(375): Illuminate\\Queue\\Worker->process()
#33 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\\Queue\\Worker->runJob()
#34 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(147): Illuminate\\Queue\\Worker->daemon()
#35 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(130): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#36 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#37 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#38 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#39 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#40 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#41 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#42 /var/www/bookstack/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute()
#43 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\\Component\\Console\\Command\\Command->run()
#44 /var/www/bookstack/vendor/symfony/console/Application.php(1014): Illuminate\\Console\\Command->run()
#45 /var/www/bookstack/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#46 /var/www/bookstack/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#47 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#48 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#49 /var/www/bookstack/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#50 {main}
"}
```
</details> 

<details><summary>bookstack-queue.service</summary>

`journalctl -u bookstack-queue`

```
Jul 06 04:32:48 gc-nl-01 php[565801]:   2023-07-06 04:32:48 BookStack\Notifications\ResetPassword .......... RUNNING
Jul 06 04:32:48 gc-nl-01 php[565801]:   2023-07-06 04:32:48 BookStack\Notifications\ResetPassword ...... 1.67ms FAIL
```

</details> 

### Expected Behaviour

1. no errors in log files
2. mail sent

### Browser Details

No matters

### Exact BookStack Version

23.06.1

### PHP Version

8.2.7

### Hosting Environment

Installation type: manually
OS Version: AlmaLinux release 8.8 (Sapphire Caracal)

**Comment by pythoninja** [comment]
Can't reproduce anymore after restarting all services.
