### ISSUE TITLE
Can't update from v23.08.03 on Debian 12

### ISSUE THREAD

**Issue by csarlanis** [BookStackApp/BookStack#4751]
### Attempted Debugging

- [X] I have read the debugging page

### Searched GitHub Issues

- [X] I have searched GitHub for the issue.

### Describe the Scenario

I run the command "git pull origin release" and the response is

<details><summary>Details</summary>
<p>

```
From https://github.com/BookStackApp/BookStack
 * branch              release    -> FETCH_HEAD
Updating c1d30341..457adc1f
error: Your local changes to the following files would be overwritten by merge:
        .env.example.complete
        .github/ISSUE_TEMPLATE/bug_report.yml
        .github/ISSUE_TEMPLATE/feature_request.yml
        .github/ISSUE_TEMPLATE/support_request.yml
        .github/SECURITY.md
        .github/translators.txt
        .github/workflows/analyse-php.yml
        .github/workflows/lint-js.yml
        .github/workflows/lint-php.yml
        .github/workflows/test-migrations.yml
        .github/workflows/test-php.yml
        .gitignore
        app/Access/Controllers/ForgotPasswordController.php
        app/Access/Controllers/LoginController.php
        app/Access/Controllers/OidcController.php
        app/Access/Controllers/RegisterController.php
        app/Access/Controllers/ResetPasswordController.php
        app/Access/Controllers/Saml2Controller.php
        app/Access/Controllers/SocialController.php
        app/Access/Controllers/ThrottlesLogins.php
        app/Access/EmailConfirmationService.php
        app/Access/LoginService.php
        app/Access/Oidc/OidcOAuthProvider.php
        app/Access/Oidc/OidcProviderSettings.php
        app/Access/Oidc/OidcService.php
        app/Access/Saml2Service.php
        app/Access/SocialAuthService.php
        app/Access/UserInviteService.php
        app/Activity/Controllers/FavouriteController.php
        app/Activity/Controllers/WatchController.php
        app/Activity/DispatchWebhookJob.php
        app/Activity/Models/Activity.php
        app/Activity/Models/View.php
        app/Activity/Notifications/Messages/BaseActivityNotification.php
        app/Activity/Notifications/Messages/CommentCreationNotification.php
        app/Activity/Notifications/Messages/PageCreationNotification.php
        app/Activity/Notifications/Messages/PageUpdateNotification.php
        app/Activity/Tools/UserEntityWatchOptions.php
        app/Api/ApiDocsController.php
        app/Api/ApiToken.php
        app/Api/UserApiTokenController.php
        app/App/HomeController.php
        app/App/Providers/AppServiceProvider.php
        app/App/Providers/AuthServiceProvider.php
        app/App/Providers/EventServiceProvider.php
        app/App/Providers/RouteServiceProvider.php
        app/App/Providers/ThemeServiceProvider.php
        app/App/Providers/ViewTweaksServiceProvider.php
        app/App/helpers.php
        app/Config/app.php
        app/Config/mail.php
        app/Config/oidc.php
        app/Console/Commands/CleanupImagesCommand.php
        app/Console/Commands/RegenerateReferencesCommand.php
        app/Console/Commands/ResetMfaCommand.php
        app/Console/Commands/UpdateUrlCommand.php
        app/Entities/BreadcrumbsViewComposer.php
        app/Entities/Controllers/BookApiController.php
        app/Entities/Controllers/BookController.php
        app/Entities/Controllers/BookshelfApiController.php
        app/Entities/Controllers/BookshelfController.php
        app/Entities/Controllers/ChapterApiController.php
        app/Entities/Controllers/ChapterController.php
        app/Entities/Controllers/PageController.php
        app/Entities/Models/Book.php
        app/Entities/Models/BookChild.php
        app/Entities/Models/Bookshelf.php
        app/Entities/Models/Chapter.php
        app/Entities/Models/Entity.php
        app/Entities/Models/Page.php
        app/Entities/Queries/RecentlyViewed.php
        app/Entities/Queries/TopFavourites.php
        app/Entities/Repos/BaseRepo.php
        app/Entities/Repos/BookRepo.php
        app/Entities/Repos/PageRepo.php
        app/Entities/Tools/ExportFormatter.php
        app/Entities/Tools/PageContent.php
        app/Entities/Tools/TrashCan.php
        app/Exceptions/Handler.php
        app/Http/Controller.php
        app/Http/Kernel.php
        app/Http/Middleware/ApiAuthenticate.php
        app/Http/Middleware/Authenticate.php
        app/Http/Middleware/Localization.php
        app/Http/Middleware/PreventAuthenticatedResponseCaching.php
        app/Notifications/ConfirmEmail.php
        app/Notifications/MailNotification.php
        app/Notifications/ResetPassword.php
        app/Notifications/TestEmail.php
        app/Notifications/UserInvite.php
        app/Permissions/EntityPermissionEvaluator.php
        app/Permissions/JointPermissionBuilder.php
        app/Permissions/PermissionApplicator.php
        app/References/CrossLinkParser.php
        app/References/ReferenceController.php
        app/References/ReferenceFetcher.php
        app/References/ReferenceStore.php
        app/References/ReferenceUpdater.php
        app/Search/SearchController.php
        app/Search/SearchIndex.php
        app/Search/SearchOptions.php
        app/Search/SearchRunner.php
        app/Settings/MaintenanceController.php
        app/Settings/SettingController.php
        app/Setting
Aborting
```

</p>
</details> 

php version is 8.2.7.

The command git diff LICENCE gives the answer
diff --git a/LICENSE b/LICENSE
old mode 100644
new mode 100755

After 
git config core.fileMode false

### Exact BookStack Version

v23.08.3

### Log Content

<details><summary>Details</summary>
<p>

```
[2023-09-17 15:24:57] production.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = bookstack and table_name = migrations>
[stacktrace]
#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\\Database\\Connection->run()
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(392): Illuminate\\Database\\Connection->select()
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(43): Illuminate\\Database\\Connection->selectFromWriteConnection()
#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable()
#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(695): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(138): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/helpers.php(247): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(138): retry()
#9 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(114): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
#10 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(82): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#11 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(628): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#12 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(81): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#13 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#14 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#15 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#16 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
#17 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#18 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#19 /var/www/bookstack/vendor/symfony/console/Command/Command.php(291): Illuminate\\Console\\Command->execute()
#20 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Console/Command.php(152): Symfony\\Component\\Console\\Command\\Command->run()
#21 /var/www/bookstack/vendor/symfony/console/Application.php(1014): Illuminate\\Console\\Command->run()
#22 /var/www/bookstack/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#23 /var/www/bookstack/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#24 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#25 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#26 /var/www/bookstack/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle()
#27 {main}

[previous exception] [object] (PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'bookstack'@'localhost' (using password: YES) at /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Conne>
[stacktrace]
#0 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(70): PDO->__construct()
#1 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(45): Illuminate\\Database\\Connectors\\Connector->createPdoConnection()
#2 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection()
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(184): Illuminate\\Database\\Connectors\\MySqlConnector->connect()
#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(1181): call_user_func()
#6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(486): Illuminate\\Database\\Connection->getPdo()
#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(414): Illuminate\\Database\\Connection->getPdoForSelect()
#8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#9 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()
#10 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(405): Illuminate\\Database\\Connection->run()
#11 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Connection.php(392): Illuminate\\Database\\Connection->select()
#12 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(43): Illuminate\\Database\\Connection->selectFromWriteConnection()
#13 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(169): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable()
#14 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(695): Illuminate\\Database\\Migrations\\DatabaseMigrationRepository->repositoryExists()
#15 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(138): Illuminate\\Database\\Migrations\\Migrator->repositoryExists()
#16 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Support/helpers.php(247): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#17 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(138): retry()
#18 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(114): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->repositoryExists()
#19 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(82): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->prepareDatabase()
#20 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(628): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->Illuminate\\Database\\Console\\Migrations\\{closure}()
#21 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(81): Illuminate\\Database\\Migrations\\Migrator->usingConnection()
#22 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#23 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#24 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#25 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod()
```

</p>
</details> 

### Hosting Environment

Debian 12

**Comment by ssddanbrown** [comment]
Hi @csarlanis,
Are you saying the provided `git pull origin release` output was after running `git config core.fileMode false` in your BookStack install directory?

**Comment by csarlanis** [comment]
Hi,
The above response was before execute the command " git config core.fileMode false " . After executing it i get the response

From https://github.com/BookStackApp/BookStack
 * branch              release    -> FETCH_HEAD
Updating c1d30341..457adc1f
error: Your local changes to the following files would be overwritten by merge:
        composer.lock
Please commit your changes or stash them before you merge.
Aborting

**Comment by ssddanbrown** [comment]
Okay, you could try restoring that file to its original state via:

```
git restore composer.lock
```

Then try the update process again.

**Comment by csarlanis** [comment]
It worked. Everything was executed without any problem after that. Thank you very much. I wish a Happy 2024.

**Comment by ssddanbrown** [comment]
Great to hear! I'll therefore close this off. Happy 2024 to you too!
