### ISSUE TITLE
Error 500 upon installing

### ISSUE THREAD

**Issue by ShrekisLyf** [BookStackApp/BookStack#4853]
### Describe the Bug

I have followed the whole tutorial very precisely and ran into a http 500 after installing. i know you people like logs so here it is :)

<details><summary>Details</summary>
<p>

```
root@ppnews:/var/www/BookStack# tail -f /var/log/apache2/error.log
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_odbc' (tried: /usr/lib/php/20200930/pdo_odbc (/usr/lib/php/20200930/pdo_odbc: cannot open shared object file: No such file or directory), /usr/lib/php/20200930/pdo_odbc.so (/usr/lib/php/20200930/pdo_odbc.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_pgsql' (tried: /usr/lib/php/20200930/pdo_pgsql (/usr/lib/php/20200930/pdo_pgsql: cannot open shared object file: No such file or directory), /usr/lib/php/20200930/pdo_pgsql.so (/usr/lib/php/20200930/pdo_pgsql.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlite' (tried: /usr/lib/php/20200930/pdo_sqlite (/usr/lib/php/20200930/pdo_sqlite: cannot open shared object file: No such file or directory), /usr/lib/php/20200930/pdo_sqlite.so (/usr/lib/php/20200930/pdo_sqlite.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  Module "gd" is already loaded in Unknown on line 0
[Sun Feb 18 22:49:09.551412 2024] [mpm_prefork:notice] [pid 2682981] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operations
[Sun Feb 18 22:49:09.551502 2024] [core:notice] [pid 2682981] AH00094: Command line: '/usr/sbin/apache2'
[Sun Feb 18 22:49:12.550598 2024] [php:error] [pid 2682984] [client 46.125.66.63:57863] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/BookStack/storage/framework/views/a626fbe2b5a63439d8e640abb3660a32dcbc7bc0.php): Failed to open stream: Permission denied in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:190\nStack trace:\n#0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#2 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(190): file_put_contents()\n#3 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(185): Illuminate\\Filesystem\\Filesystem->put()\n#4 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(62): Illuminate\\View\\Compilers\\BladeCompiler->compile()\n#5 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()\n#6 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()\n#7 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()\n#8 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()\n#9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()\n#10 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()\n#11 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()\n#12 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(629): Illuminate\\Routing\\ResponseFactory->view()\n#13 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#14 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#15 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#16 /var/www/BookStack/app/Exceptions/Handler.php(89): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#17 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): BookStack\\Exceptions\\Handler->render()\n#18 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#19 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#20 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#21 {main}\n  thrown in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 190
[Sun Feb 18 22:49:12.553044 2024] [php:error] [pid 2682984] [client 46.125.66.63:57863] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/BookStack/storage/framework/views/a626fbe2b5a63439d8e640abb3660a32dcbc7bc0.php): Failed to open stream: Permission denied in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:190\nStack trace:\n#0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#2 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(190): file_put_contents()\n#3 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(185): Illuminate\\Filesystem\\Filesystem->put()\n#4 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(62): Illuminate\\View\\Compilers\\BladeCompiler->compile()\n#5 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()\n#6 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()\n#7 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()\n#8 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()\n#9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()\n#10 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()\n#11 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()\n#12 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(629): Illuminate\\Routing\\ResponseFactory->view()\n#13 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#14 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#15 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#16 /var/www/BookStack/app/Exceptions/Handler.php(89): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#17 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): BookStack\\Exceptions\\Handler->render()\n#18 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#19 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(246): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#20 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#21 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#22 {main}\n  thrown in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 190
[Sun Feb 18 22:49:13.638613 2024] [php:error] [pid 2682986] [client 46.125.66.63:57864] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/BookStack/storage/framework/views/a626fbe2b5a63439d8e640abb3660a32dcbc7bc0.php): Failed to open stream: Permission denied in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:190\nStack trace:\n#0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#2 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(190): file_put_contents()\n#3 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(185): Illuminate\\Filesystem\\Filesystem->put()\n#4 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(62): Illuminate\\View\\Compilers\\BladeCompiler->compile()\n#5 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()\n#6 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()\n#7 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()\n#8 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()\n#9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()\n#10 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()\n#11 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()\n#12 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(629): Illuminate\\Routing\\ResponseFactory->view()\n#13 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#14 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#15 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#16 /var/www/BookStack/app/Exceptions/Handler.php(89): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#17 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): BookStack\\Exceptions\\Handler->render()\n#18 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#19 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#20 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#21 {main}\n  thrown in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 190
[Sun Feb 18 22:49:13.639487 2024] [php:error] [pid 2682986] [client 46.125.66.63:57864] PHP Fatal error:  Uncaught ErrorException: file_put_contents(/var/www/BookStack/storage/framework/views/a626fbe2b5a63439d8e640abb3660a32dcbc7bc0.php): Failed to open stream: Permission denied in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:190\nStack trace:\n#0 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()\n#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#2 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(190): file_put_contents()\n#3 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(185): Illuminate\\Filesystem\\Filesystem->put()\n#4 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(62): Illuminate\\View\\Compilers\\BladeCompiler->compile()\n#5 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(195): Illuminate\\View\\Engines\\CompilerEngine->get()\n#6 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(178): Illuminate\\View\\View->getContents()\n#7 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/View/View.php(147): Illuminate\\View\\View->renderContents()\n#8 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(69): Illuminate\\View\\View->render()\n#9 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\\Http\\Response->setContent()\n#10 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Illuminate\\Http\\Response->__construct()\n#11 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(87): Illuminate\\Routing\\ResponseFactory->make()\n#12 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(629): Illuminate\\Routing\\ResponseFactory->view()\n#13 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(554): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#14 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(460): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#15 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(377): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#16 /var/www/BookStack/app/Exceptions/Handler.php(89): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#17 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(233): BookStack\\Exceptions\\Handler->render()\n#18 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(210): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#19 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(246): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#20 /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(270): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#21 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#22 {main}\n  thrown in /var/www/BookStack/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php on line 190
```

</p>
</details> 

### Steps to Reproduce

1. Basically followed to install
2. go to sapari.ppnews.eu

### Expected Behaviour

It *should* load the site as expected

### Exact BookStack Version

Newest https://github.com/BookStackApp/BookStack.git --branch release --single-branch

**Comment by ssddanbrown** [comment]
Hi @ShrekisLyf,

Looks like you have an issue with filesystem permissions.
We have some guidance for that here:
https://www.bookstackapp.com/docs/admin/filesystem-permissions/

If you need further help, it would be useful to know the operating system used, and the tutorial followed.

**Comment by ShrekisLyf** [comment]
wow that REALLY fixed it!
that part was not in the installation documentation with the sudo chown -R user:www-data /var/www/BookStack and sudo chmod -R 755 /var/www/BookStack but that did the trick!

**Comment by ssddanbrown** [comment]
Good to hear that fixed it.

> that part was not in the installation documentation

Our manual install steps do advise to ensure these folders are writable on step 4:

> 4. Ensure the storage, bootstrap/cache & public/uploads folders are writable by the web server ([More information here](https://www.bookstackapp.com/docs/admin/filesystem-permissions/)).
