### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'system_name' in 'where clause'

### ISSUE THREAD

**Issue by georgelouk** [BookStackApp/BookStack#4979]
### Describe the Bug

I've installed "release" version and it seems randomly (and not at the same place each time) i get an http error 500 as user.

The laravel logs show : 

<details><summary>Details</summary>
<p>

```
[2024-04-30 09:52:28] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'system_name' in 'where clause' (SQL: select * from `users` where `system_name` = public limit 1) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'system_name' in 'where clause' (SQL: select * from `users` where `system_name` = public limit 1) at C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:760)
[stacktrace]
#0 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(405): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2705): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#3 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2694): Illuminate\\Database\\Query\\Builder->runSelect()
#4 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(3230): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#5 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2693): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#6 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(710): Illuminate\\Database\\Query\\Builder->get(Array)
#7 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(694): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#8 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\BuildsQueries.php(296): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#9 C:\\wamp64\\www\\bookstack\\app\\App\\Providers\\AuthServiceProvider.php(73): Illuminate\\Database\\Eloquent\\Builder->first()
#10 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(885): BookStack\\App\\Providers\\AuthServiceProvider->BookStack\\App\\Providers\\{closure}(Object(BookStack\\App\\Application), Array)
#11 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(770): Illuminate\\Container\\Container->build(Object(Closure))
#12 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(856): Illuminate\\Container\\Container->resolve('users.default', Array, true)
#13 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(706): Illuminate\\Foundation\\Application->resolve('users.default', Array)
#14 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(841): Illuminate\\Container\\Container->make('users.default', Array)
#15 C:\\wamp64\\www\\bookstack\\app\\Users\\Models\\User.php(98): Illuminate\\Foundation\\Application->make('users.default')
#16 C:\\wamp64\\www\\bookstack\\app\\App\\helpers.php(38): BookStack\\Users\\Models\\User::getGuest()
#17 C:\\wamp64\\www\\bookstack\\app\\Http\\Middleware\\Localization.php(26): user()
#18 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): BookStack\\Http\\Middleware\\Localization->handle(Object(BookStack\\Http\\Request), Object(Closure))
#19 C:\\wamp64\\www\\bookstack\\app\\Http\\Middleware\\RunThemeActions.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#20 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): BookStack\\Http\\Middleware\\RunThemeActions->handle(Object(BookStack\\Http\\Request), Object(Closure))
#21 C:\\wamp64\\www\\bookstack\\app\\Http\\Middleware\\CheckEmailConfirmed.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#22 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): BookStack\\Http\\Middleware\\CheckEmailConfirmed->handle(Object(BookStack\\Http\\Request), Object(Closure))
#23 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#24 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(BookStack\\Http\\Request), Object(Closure))
#25 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#26 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(BookStack\\Http\\Request), Object(Closure))
#27 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#28 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(BookStack\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#29 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(BookStack\\Http\\Request), Object(Closure))
#30 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#31 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(BookStack\\Http\\Request), Object(Closure))
#32 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#33 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(BookStack\\Http\\Request), Object(Closure))
#34 C:\\wamp64\\www\\bookstack\\app\\Http\\Middleware\\ApplyCspRules.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#35 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): BookStack\\Http\\Middleware\\ApplyCspRules->handle(Object(BookStack\\Http\\Request), Object(Closure))
#36 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#37 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(797): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(BookStack\\Http\\Request))
#39 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(740): Illuminate\\Routing\\Router->runRoute(Object(BookStack\\Http\\Request), Object(Illuminate\\Routing\\Route))
#40 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute(Object(BookStack\\Http\\Request))
#41 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(190): Illuminate\\Routing\\Router->dispatch(Object(BookStack\\Http\\Request))
#42 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(BookStack\\Http\\Request))
#43 C:\\wamp64\\www\\bookstack\\app\\Http\\Middleware\\PreventResponseCaching.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#44 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): BookStack\\Http\\Middleware\\PreventResponseCaching->handle(Object(BookStack\\Http\\Request), Object(Closure))
#45 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#46 C:\\wamp64\\www\\bookstack\\app\\Http\\Middleware\\TrustProxies.php(41): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(BookStack\\Http\\Request), Object(Closure))
#47 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): BookStack\\Http\\Middleware\\TrustProxies->handle(Object(BookStack\\Http\\Request), Object(Closure))
#48 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#49 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(BookStack\\Http\\Request), Object(Closure))
#50 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(BookStack\\Http\\Request), Object(Closure))
#51 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#52 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(BookStack\\Http\\Request), Object(Closure))
#53 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#54 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(BookStack\\Http\\Request), Object(Closure))
#55 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#56 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#57 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(BookStack\\Http\\Request))
#58 C:\\wamp64\\www\\bookstack\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(BookStack\\Http\\Request))
#59 {main}

[previous exception] [object] (PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'system_name' in 'where clause' at C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:414)
[stacktrace]
#0 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(414): PDO->prepare('select * from `...')
#1 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from `...', Array)
#2 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#3 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php(405): Illuminate\\Database\\Connection->run('select * from `...', Array, Object(Closure))
#4 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2705): Illuminate\\Database\\Connection->select('select * from `...', Array, true)
#5 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2694): Illuminate\\Database\\Query\\Builder->runSelect()
#6 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(3230): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#7 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Query\\Builder.php(2693): Illuminate\\Database\\Query\\Builder->onceWithColumns(Array, Object(Closure))
#8 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(710): Illuminate\\Database\\Query\\Builder->get(Array)
#9 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Eloquent\\Builder.php(694): Illuminate\\Database\\Eloquent\\Builder->getModels(Array)
#10 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\BuildsQueries.php(296): Illuminate\\Database\\Eloquent\\Builder->get(Array)
#11 C:\\wamp64\\www\\bookstack\\app\\App\\Providers\\AuthServiceProvider.php(73): Illuminate\\Database\\Eloquent\\Builder->first()
#12 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(885): BookStack\\App\\Providers\\AuthServiceProvider->BookStack\\App\\Providers\\{closure}(Object(BookStack\\App\\Application), Array)
#13 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(770): Illuminate\\Container\\Container->build(Object(Closure))
#14 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(856): Illuminate\\Container\\Container->resolve('users.default', Array, true)
#15 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(706): Illuminate\\Foundation\\Application->resolve('users.default', Array)
#16 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Application.php(841): Illuminate\\Container\\Container->make('users.default', Array)
#17 C:\\wamp64\\www\\bookstack\\app\\Users\\Models\\User.php(98): Illuminate\\Foundation\\Application->make('users.default')
#18 C:\\wamp64\\www\\bookstack\\app\\App\\helpers.php(38): BookStack\\Users\\Models\\User::getGuest()
#19 C:\\wamp64\\www\\bookstack\\app\\Http\\Middleware\\Localization.php(26): user()
#20 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): BookStack\\Http\\Middleware\\Localization->handle(Object(BookStack\\Http\\Request), Object(Closure))
#21 C:\\wamp64\\www\\bookstack\\app\\Http\\Middleware\\RunThemeActions.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#22 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): BookStack\\Http\\Middleware\\RunThemeActions->handle(Object(BookStack\\Http\\Request), Object(Closure))
#23 C:\\wamp64\\www\\bookstack\\app\\Http\\Middleware\\CheckEmailConfirmed.php(47): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#24 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): BookStack\\Http\\Middleware\\CheckEmailConfirmed->handle(Object(BookStack\\Http\\Request), Object(Closure))
#25 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#26 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(BookStack\\Http\\Request), Object(Closure))
#27 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#28 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(BookStack\\Http\\Request), Object(Closure))
#29 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#30 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(BookStack\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#31 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(BookStack\\Http\\Request), Object(Closure))
#32 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#33 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(BookStack\\Http\\Request), Object(Closure))
#34 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#35 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(BookStack\\Http\\Request), Object(Closure))
#36 C:\\wamp64\\www\\bookstack\\app\\Http\\Middleware\\ApplyCspRules.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#37 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): BookStack\\Http\\Middleware\\ApplyCspRules->handle(Object(BookStack\\Http\\Request), Object(Closure))
#38 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#39 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(797): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#40 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(BookStack\\Http\\Request))
#41 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(740): Illuminate\\Routing\\Router->runRoute(Object(BookStack\\Http\\Request), Object(Illuminate\\Routing\\Route))
#42 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute(Object(BookStack\\Http\\Request))
#43 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(190): Illuminate\\Routing\\Router->dispatch(Object(BookStack\\Http\\Request))
#44 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(BookStack\\Http\\Request))
#45 C:\\wamp64\\www\\bookstack\\app\\Http\\Middleware\\PreventResponseCaching.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#46 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): BookStack\\Http\\Middleware\\PreventResponseCaching->handle(Object(BookStack\\Http\\Request), Object(Closure))
#47 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Middleware\\TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#48 C:\\wamp64\\www\\bookstack\\app\\Http\\Middleware\\TrustProxies.php(41): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(BookStack\\Http\\Request), Object(Closure))
#49 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): BookStack\\Http\\Middleware\\TrustProxies->handle(Object(BookStack\\Http\\Request), Object(Closure))
#50 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#51 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(BookStack\\Http\\Request), Object(Closure))
#52 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(BookStack\\Http\\Request), Object(Closure))
#53 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#54 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(BookStack\\Http\\Request), Object(Closure))
#55 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#56 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(BookStack\\Http\\Request), Object(Closure))
#57 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(BookStack\\Http\\Request))
#58 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#59 C:\\wamp64\\www\\bookstack\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(BookStack\\Http\\Request))
#60 C:\\wamp64\\www\\bookstack\\public\\index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(BookStack\\Http\\Request))
#61 {main}
"} 
```

</p>
</details> 

### Steps to Reproduce

1. Install Bookstack 'release' version
2. Just browse in various pages in the web application

### Expected Behaviour

Not to show that error. The error observed in many pcs Macs and Windows.

### Browser Details

Chrome 124 on Mac

### Exact BookStack Version

v24.02.3

**Comment by ssddanbrown** [comment]
Hi @georgelouk,

- How often does this arise?
- Can this occur by refreshing a single view over again? If so, how many errors vs successes do you see?
- Are you comfortable accessing the database in your environment?

**Comment by georgelouk** [comment]
Hi @ssddanbrown 

- Every 3 to 10 clicks around it arises 
- nope. When it occurs and i refresh the page, i access it succesfully. I cannot replicate it with refresh. For example it occured at /settings/features. I refreshed and i started to refresh again and again and it didn't happen again.
- Yes sure

**Comment by georgelouk** [comment]
Finally replicated with refresh, but i clicked many times refresh till it happen.

**Comment by ssddanbrown** [comment]
If you run `php artisan config:cache` from your BookStack install directory, does the issue remain?

**Comment by georgelouk** [comment]
I run it, and it seems that it is ok now. Let's close it and if it happen again i will re-open this ticket. 
Thank you!

**Comment by ssddanbrown** [comment]
Since that seems to work, it's an indicator of thread safety which can affect env option loading, and issues are more commonly found in Windows environments. It depends on specific versions of software in use though.
Generally I'd only advise WAMP/XAMPP setups for development or personal use since there's more likely to be unconventional issues that pop up, while being harder for us to support on.

**Note:** you will need to ensure you re-run that `php artisan config:cache` command on each update or change to the `.env` file otherwise you'll run into more issues.

**Comment by georgelouk** [comment]
Ok thanks a lot, we might build our books on wamp but if it is needed to transfer it later on a better web server.
Thanks a lot again! You've done excellent work.
