### ISSUE TITLE
Page not saving

### ISSUE THREAD

**Issue by luizeof** [BookStackApp/BookStack#536]
### For Feature Requests

Desired Feature:

### For Bug Reports

2017-09-29T08:12:05.876670067Z [Fri Sep 29 08:12:05.876357 2017] [:error] [pid 110] [client 172.17.0.8:50548] [2017-09-29 08:12:05] production.ERROR: Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Type error: Argument 1 passed to BookStack\\Repos\\EntityRepo::pageToPlainText() must be an instance of BookStack\\Page, string given, called in /var/www/bookstack/app/Repos/EntityRepo.php on line 574 in /var/www/bookstack/app/Repos/EntityRepo.php:721\nStack trace:\n#0 /var/www/bookstack/app/Repos/EntityRepo.php(574): BookStack\\Repos\\EntityRepo->pageToPlainText('')\n#1 /var/www/bookstack/app/Http/Controllers/PageController.php(136): BookStack\\Repos\\EntityRepo->publishPageDraft(Object(BookStack\\Page), Array)\n#2 [internal function]: BookStack\\Http\\Controllers\\PageController->store(Object(Illuminate\\Http\\Request), 'docker', '1')\n#3 

* BookStack Version: latest
* PHP Version: 7.0
* MySQL Version: Maria 10.1

**Comment by btannous** [comment]
+1 here.
Bookstack: 0.17.2
https://github.com/solidnerd/docker-bookstack
mysql: 5.7.12

```
[Fri Sep 29 23:04:26.007180 2017] [:error] [pid 109] [client 172.19.0.2:47934] [2017-09-29 23:04:26] production.ERROR: Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Type error: Argument 1 passed to BookStack\\Repos\\EntityRepo::pageToPlainText() must be an instance of BookStack\\Page, string given, called in /var/www/bookstack/app/Repos/EntityRepo.php on line 574 in /var/www/bookstack/app/Repos/EntityRepo.php:721
Stack trace:
#0 /var/www/bookstack/app/Repos/EntityRepo.php(574): BookStack\\Repos\\EntityRepo->pageToPlainText('<p id="bkmrk-te...')
#1 /var/www/bookstack/app/Http/Controllers/PageController.php(136): BookStack\\Repos\\EntityRepo->publishPageDraft(Object(BookStack\\Page), Array)
#2 [internal function]: BookStack\\Http\\Controllers\\PageController->store(Object(Illuminate\\Http\\Request), 'ams-networking-...', '363')
#3 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#4 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\\Routing\\Controller->callAction('store', Array)
#5 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(BookStack\\Http\\Controllers\\PageController), 'store')
#6 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\\Routing\\Route->runController()
#7 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(559): Illuminate\\Routing\\Route->run()
#8 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /var/www/bookstack/app/Http/Controllers/Controller.php(44): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(131): BookStack\\Http\\Controllers\\Controller->BookStack\\Http\\Controllers\\{closure}(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /var/www/bookstack/app/Http/Middleware/Authenticate.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): BookStack\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/bookstack/app/Http/Middleware/Localization.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): BookStack\\Http\\Middleware\\Localization->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#33 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#34 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#35 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/bookstack/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/w
```

**Comment by ssddanbrown** [comment]
@luizeof Please can you go into settings and fully confirm the exact BookStack version you are running?

**Comment by btannous** [comment]
In my case, a revert back to 0.17.0 fixed the issue.

**Comment by ssddanbrown** [comment]
Pretty sure this has been fixed in a more recent version of BookStack. If you upgrade and still experience the same issue just comment and this can be re-opened.

**Comment by luizeof** [comment]
@ssddanbrown there are a Docker version of BookStack beta?

**Comment by btannous** [comment]
@ssddanbrown 0.18.4 fixes the issue for me.  Thanks!
